package:
  name: m2-mingw-w64-pcre
  version: '8.37'
source:
  url: http://repo.msys2.org/mingw/sources/mingw-w64-pcre-8.37-2.src.tar.gz
  md5: 936524317a13f7da01ff4676bdb271e2
build:
  number: '2'
requirements:
  run:
  - m2-mingw-w64-gcc-libs
  - m2-mingw-w64-bzip2
  - m2-mingw-w64-wineditline
  - m2-mingw-w64-zlib
about:
  home: http://pcre.org
  license: BSD
  summary: A library that implements Perl 5-style regular expressions (mingw-w64)
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/mingw/i686/mingw-w64-i686-pcre-8.37-2-any.pkg.tar.xz
      md5: f87e7c00bd713b41e1787e9172beebdd
      mv-src: mingw32
      mv-dst: Library/mingw-w64
    win-64:
      url: http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-pcre-8.37-2-any.pkg.tar.xz
      md5: 351bdf7b78ee5da2e524986c89b0a83e
      mv-src: mingw64
      mv-dst: Library/mingw-w64
