package:
  name: m2-msys2-libasprintf
  version: 0.19.7
source:
  url: http://repo.msys2.org/msys/sources/libasprintf-0.19.7-3.src.tar.gz
  md5: baadc0debaadc0debaadc0debaadc0de
build:
  number: '3'
requirements:
  run:
  - m2-msys2-gcc-libs
about:
  home: https://www.gnu.org/software/gettext/
  license: GPL
  summary: C-style formatted output in C++ (runtime)
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/msys/i686/libasprintf-0.19.7-3-i686.pkg.tar.xz
      md5: 3e3270bc1a7223d1e44e93d1944de753
      mv-src: '*'
      mv-dst: Library/
    win-64:
      url: http://repo.msys2.org/msys/x86_64/libasprintf-0.19.7-3-x86_64.pkg.tar.xz
      md5: 06ca6c6e2eb98cd5e0bf8d4330a03827
      mv-src: '*'
      mv-dst: Library/
