package:
  name: m2-mingw-w64-toolchain
  version: 5.3.0
build:
  number: '5'
requirements:
  run:
  - mingw-w64-binutils
  - mingw-w64-crt-git
  - mingw-w64-gcc
  - mingw-w64-gcc-ada
  - mingw-w64-gcc-fortran
  - mingw-w64-gcc-libgfortran
  - mingw-w64-gcc-libs
  - mingw-w64-gcc-objc
  - mingw-w64-headers-git
  - mingw-w64-libmangle-git
  - mingw-w64-libwinpthread-git
  - mingw-w64-make
  - mingw-w64-pkg-config
  - mingw-w64-tools-git
  - mingw-w64-winpthreads-git
