package:
  name: m2-msys2-openssh
  version: 7.1p2
source:
  url: http://repo.msys2.org/msys/sources/openssh-7.1p2-1.src.tar.gz
  md5: 2a4992c0ce47777018036139739ec81d
build:
  number: '1'
requirements:
  run:
  - m2-msys2-heimdal
  - m2-msys2-libedit
  - m2-msys2-libcrypt
  - m2-msys2-openssl
about:
  home: http://www.openssh.org/portable.html
  license: GPL (msys-2.0.dll linkage), custom:BSD
  summary: Free version of the SSH connectivity tools
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/msys/i686/openssh-7.1p2-1-i686.pkg.tar.xz
      md5: d9c9c2af04bb2e3dbd6923208cb5e2f4
      mv-src: '*'
      mv-dst: Library/
    win-64:
      url: http://repo.msys2.org/msys/x86_64/openssh-7.1p2-1-x86_64.pkg.tar.xz
      md5: 06b2f04a821c1741f40efc007e90598b
      mv-src: '*'
      mv-dst: Library/
