package:
  name: m2-msys2-libpipeline
  version: 1.4.0
source:
  url: http://repo.msys2.org/msys/sources/libpipeline-1.4.0-1.src.tar.gz
  md5: baadc0debaadc0debaadc0debaadc0de
build:
  number: '1'
requirements:
  run:
  - m2-msys2-gcc-libs
about:
  home: http://libpipeline.nongnu.org/
  license: GPL (msys-2.0.dll linkage), BSD
  summary: a C library for manipulating pipelines of subprocesses in a flexible and
    convenient way
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/msys/i686/libpipeline-1.4.0-1-i686.pkg.tar.xz
      md5: 973d38bc96ceee796eb1f328e005d362
      mv-src: '*'
      mv-dst: Library/
    win-64:
      url: http://repo.msys2.org/msys/x86_64/libpipeline-1.4.0-1-x86_64.pkg.tar.xz
      md5: 85a1e5a0eca7895edef6b5829fcea3c4
      mv-src: '*'
      mv-dst: Library/
