package:
  name: m2-mingw-w64-curl
  version: 7.47.1
source:
  url: http://repo.msys2.org/mingw/sources/mingw-w64-curl-7.47.1-1.src.tar.gz
  md5: e6c9ed9854e085e4dbf073abf4968733
build:
  number: '1'
requirements:
  run:
  - m2-mingw-w64-gcc-libs
  - m2-mingw-w64-c-ares
  - m2-mingw-w64-libidn
  - m2-mingw-w64-libssh2
  - m2-mingw-w64-zlib
  - m2-mingw-w64-rtmpdump-git
  - m2-mingw-w64-ca-certificates
  - m2-mingw-w64-openssl
about:
  home: https://curl.haxx.se
  license: MIT
  summary: An URL retrival utility and library. (mingw-w64)
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/mingw/i686/mingw-w64-i686-curl-7.47.1-1-any.pkg.tar.xz
      md5: 22a3bff52fc5b6c3da8162a2af3423c7
      mv-src: mingw32
      mv-dst: Library/mingw-w64
    win-64:
      url: http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-curl-7.47.1-1-any.pkg.tar.xz
      md5: 3289509f650020dbc9bbe438536529d9
      mv-src: mingw64
      mv-dst: Library/mingw-w64
