package:
  name: m2-msys2-libpcre32
  version: '8.38'
source:
  url: http://repo.msys2.org/msys/sources/libpcre32-8.38-1.src.tar.gz
  md5: 936524317a13f7da01ff4676bdb271e2
build:
  number: '1'
requirements:
  run:
  - m2-msys2-gcc-libs
about:
  home: http://www.pcre.org/
  license: GPL, BSD
  summary: A library that implements Perl 5-style regular expressions
extra:
  msys2-binaries:
    win-32:
      srcpkg: msys/libpcre32
      url: http://repo.msys2.org/msys/i686/libpcre32-8.38-1-i686.pkg.tar.xz
      md5: 5c428380194def570ba3424296d36023
      mv-src: '*'
      mv-dst: Library/
    win-64:
      srcpkg: msys/libpcre32
      url: http://repo.msys2.org/msys/x86_64/libpcre32-8.38-1-x86_64.pkg.tar.xz
      md5: dddd6b639af984a644b755f5372404ad
      mv-src: '*'
      mv-dst: Library/
