package:
  name: m2-mingw-w64-winpthreads-git
  version: 5.0.0.4573.628fdbf
source:
  url: http://repo.msys2.org/mingw/sources/mingw-w64-winpthreads-git-5.0.0.4573.628fdbf-1.src.tar.gz
  md5: 22d68c9d3091b0f2818920c2c10c7cb7
build:
  number: '1'
requirements:
  run:
  - m2-mingw-w64-crt-git
  - m2-mingw-w64-libwinpthread-git
about:
  home: http://mingw-w64.sourceforge.net
  license: MIT, BSD
  summary: MinGW-w64 winpthreads library
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/mingw/i686/mingw-w64-i686-winpthreads-git-5.0.0.4573.628fdbf-1-any.pkg.tar.xz
      md5: 711e5c38dc49aa77fb7eba2f133e7d55
      mv-src: mingw32
      mv-dst: Library/mingw-w64
    win-64:
      url: http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-winpthreads-git-5.0.0.4573.628fdbf-1-any.pkg.tar.xz
      md5: 8b138fe4965fabbf90de3ac783725844
      mv-src: mingw64
      mv-dst: Library/mingw-w64
