package:
  name: m2-msys2-libcrypt
  version: '1.1'
source:
  url: http://repo.msys2.org/msys/sources/libcrypt-1.1-6.src.tar.gz
  md5: baadc0debaadc0debaadc0debaadc0de
build:
  number: '6'
requirements:
  run:
  - m2-msys2-gcc-libs
about:
  home: http://cygwin.com/
  license: GPL (msys-2.0.dll linkage), custom
  summary: Encryption/Decryption utility and library
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/msys/i686/libcrypt-1.1-6-i686.pkg.tar.xz
      md5: ac77df8845118ab4c1a3c393d2a91289
      mv-src: '*'
      mv-dst: Library/
    win-64:
      url: http://repo.msys2.org/msys/x86_64/libcrypt-1.1-6-x86_64.pkg.tar.xz
      md5: 81bb482446043dd6394bd8ac53b797ac
      mv-src: '*'
      mv-dst: Library/
