package:
  name: m2-msys2-perl-net-http
  version: '6.09'
source:
  url: http://repo.msys2.org/msys/sources/perl-Net-HTTP-6.09-1.src.tar.gz
  md5: 936524317a13f7da01ff4676bdb271e2
build:
  number: '1'
requirements:
  run:
  - m2-msys2-perl
about:
  home: http://search.cpan.org/dist/Net-HTTP
  license: PerlArtistic, GPL
  summary: Low-level HTTP connection (client)
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/msys/i686/perl-Net-HTTP-6.09-1-any.pkg.tar.xz
      md5: 152399acb29179f4de450e00551c28ce
      mv-src: '*'
      mv-dst: Library/
    win-64:
      url: http://repo.msys2.org/msys/x86_64/perl-Net-HTTP-6.09-1-any.pkg.tar.xz
      md5: a9ce62b9268bff39fba985fcd89c0cee
      mv-src: '*'
      mv-dst: Library/
