package:
  name: m2-mingw-w64-tcl
  version: 8.6.5
source:
  url: http://repo.msys2.org/mingw/sources/mingw-w64-tcl-8.6.5-1.src.tar.gz
  md5: 731f7aadd90c856bb33e085a4a956235
build:
  number: '1'
requirements:
  run:
  - m2-mingw-w64-gcc-libs
  - m2-mingw-w64-zlib
about:
  home: http://tcl.sourceforge.net
  license: custom
  summary: The Tcl scripting language (mingw-w64)
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/mingw/i686/mingw-w64-i686-tcl-8.6.5-1-any.pkg.tar.xz
      md5: cd53c7142c4b3ff9555361e94b5b3a60
      mv-src: mingw32
      mv-dst: Library/mingw-w64
    win-64:
      url: http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-tcl-8.6.5-1-any.pkg.tar.xz
      md5: 64dfe5207b548bed0a5cbf08bae3b76a
      mv-src: mingw64
      mv-dst: Library/mingw-w64
