package:
  name: m2-mingw-w64-libsodium
  version: 1.0.10
source:
  url: http://repo.msys2.org/mingw/sources/mingw-w64-libsodium-1.0.10-1.src.tar.gz
  md5: eaa16338e1ab82c487990108a74e716b
build:
  number: '1'
requirements:
  run:
  - m2-mingw-w64-gcc-libs
about:
  home: https://github.com/jedisct1/libsodium
  license: custom:ISC
  summary: P(ortable|ackageable) NaCl-based crypto library (mingw-w64)
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/mingw/i686/mingw-w64-i686-libsodium-1.0.10-1-any.pkg.tar.xz
      md5: f26aaab8ca6e9e989d6f2a1b6f86c4be
      mv-src: mingw32
      mv-dst: Library/mingw-w64
    win-64:
      url: http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-libsodium-1.0.10-1-any.pkg.tar.xz
      md5: 5243fb05901dcc506d2f8217339c6971
      mv-src: mingw64
      mv-dst: Library/mingw-w64
