package:
  name: m2-msys2-tar
  version: '1.28'
source:
  url: http://repo.msys2.org/msys/sources/tar-1.28-3.src.tar.gz
  md5: baadc0debaadc0debaadc0debaadc0de
build:
  number: '3'
requirements:
  run:
  - m2-msys2-msys2-runtime
  - m2-msys2-libiconv
  - m2-msys2-libintl
  - m2-msys2-bash
about:
  home: http://www.gnu.org/software/tar/tar.html
  license: GPL (msys-2.0.dll linkage), GPL3
  summary: Utility used to store, backup, and transport files
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/msys/i686/tar-1.28-3-i686.pkg.tar.xz
      md5: 6afa7cc6fff0d7045bb8f5371edfb6ab
      mv-src: '*'
      mv-dst: Library/
    win-64:
      url: http://repo.msys2.org/msys/x86_64/tar-1.28-3-x86_64.pkg.tar.xz
      md5: acded7bb5518a65a4abc92f7fc3b7a48
      mv-src: '*'
      mv-dst: Library/
