package:
  name: m2-msys2-libpcreposix
  version: '8.38'
source:
  url: http://repo.msys2.org/msys/sources/libpcreposix-8.38-1.src.tar.gz
  md5: 936524317a13f7da01ff4676bdb271e2
build:
  number: '1'
requirements:
  run:
  - m2-msys2-libpcre
about:
  home: http://www.pcre.org/
  license: GPL, BSD
  summary: A library that implements Perl 5-style regular expressions
extra:
  msys2-binaries:
    win-32:
      srcpkg: msys/libpcreposix
      url: http://repo.msys2.org/msys/i686/libpcreposix-8.38-1-i686.pkg.tar.xz
      md5: 08d62daf4d874d066d2360f57fdf2aed
      mv-src: '*'
      mv-dst: Library/
    win-64:
      srcpkg: msys/libpcreposix
      url: http://repo.msys2.org/msys/x86_64/libpcreposix-8.38-1-x86_64.pkg.tar.xz
      md5: 81e3ec40957d8dfa749319a84ce1df75
      mv-src: '*'
      mv-dst: Library/
