package:
  name: m2-mingw-w64-libtasn1
  version: '4.7'
source:
  url: http://repo.msys2.org/mingw/sources/mingw-w64-libtasn1-4.7-1.src.tar.gz
  md5: c8c4a94da06819eef222ef79ed49492b
build:
  number: '1'
requirements:
  run:
  - m2-mingw-w64-gcc-libs
about:
  home: http://www.gnu.org/software/libtasn1/
  license: GPL3, LGPL
  summary: A library for Abstract Syntax Notation One (ASN.1) and Distinguish Encoding
    Rules (DER) manipulation (mingw-w64)
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/mingw/i686/mingw-w64-i686-libtasn1-4.7-1-any.pkg.tar.xz
      md5: c434ce3096dfef7fbd6aba1f4737b0e9
      mv-src: mingw32
      mv-dst: Library/mingw-w64
    win-64:
      url: http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-libtasn1-4.7-1-any.pkg.tar.xz
      md5: 06781bf90f54ac85da4ed09f1aa92873
      mv-src: mingw64
      mv-dst: Library/mingw-w64
