package:
  name: m2-msys2-gdbm
  version: '1.11'
source:
  url: http://repo.msys2.org/msys/sources/gdbm-1.11-3.src.tar.gz
  md5: baadc0debaadc0debaadc0debaadc0de
build:
  number: '3'
requirements:
  run:
  - m2-msys2-libgdbm
about:
  home: http://www.gnu.org/software/gdbm/gdbm.html
  license: GPL (msys-2.0.dll linkage), GPL3
  summary: GNU database library
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/msys/i686/gdbm-1.11-3-i686.pkg.tar.xz
      md5: e059691a5eb019e5a9c71c5d4e0c39c5
      mv-src: '*'
      mv-dst: Library/
    win-64:
      url: http://repo.msys2.org/msys/x86_64/gdbm-1.11-3-x86_64.pkg.tar.xz
      md5: baa7a26f73989d5ab33d0c8a5c97aa24
      mv-src: '*'
      mv-dst: Library/
