package:
  name: m2-mingw-w64-libidn
  version: '1.32'
source:
  url: http://repo.msys2.org/mingw/sources/mingw-w64-libidn-1.32-3.src.tar.gz
  md5: af26624e5337a1bbb2cc21eb69c79583
build:
  number: '3'
requirements:
  run:
  - m2-mingw-w64-gettext
about:
  home: https://www.gnu.org/software/libidn
  license: GPL3, LGPL
  summary: Implementation of the Stringprep, Punycode and IDNA specifications (mingw-w64)
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/mingw/i686/mingw-w64-i686-libidn-1.32-3-any.pkg.tar.xz
      md5: 9ecd264a3da0f0f6af8b392c1b183a7b
      mv-src: mingw32
      mv-dst: Library/mingw-w64
    win-64:
      url: http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-libidn-1.32-3-any.pkg.tar.xz
      md5: 6f68259e17b68bbf19efc7b4fb5c1968
      mv-src: mingw64
      mv-dst: Library/mingw-w64
