package:
  name: m2-msys2-perl-net-smtp-ssl
  version: '1.02'
source:
  url: http://repo.msys2.org/msys/sources/perl-Net-SMTP-SSL-1.02-1.src.tar.gz
  md5: 936524317a13f7da01ff4676bdb271e2
build:
  number: '1'
requirements:
  run:
  - m2-msys2-perl-io-socket-ssl
about:
  home: http://search.cpan.org/dist/Net-SMTP-SSL/
  license: GPL, PerlArtistic
  summary: SSL support for Net::SMTP
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/msys/i686/perl-Net-SMTP-SSL-1.02-1-any.pkg.tar.xz
      md5: 61eed7bb3b7e926b92858683a32b3ccb
      mv-src: '*'
      mv-dst: Library/
    win-64:
      url: http://repo.msys2.org/msys/x86_64/perl-Net-SMTP-SSL-1.02-1-any.pkg.tar.xz
      md5: f78a2310abd8803f3687587dcf4c4c4a
      mv-src: '*'
      mv-dst: Library/
