package:
  name: m2-msys2-info
  version: '6.0'
source:
  url: http://repo.msys2.org/msys/sources/info-6.0-1.src.tar.gz
  md5: 936524317a13f7da01ff4676bdb271e2
build:
  number: '1'
requirements:
  run:
  - m2-msys2-ncurses
  - m2-msys2-libintl
  - m2-msys2-gzip
about:
  home: http://www.gnu.org/software/texinfo/
  license: GPL (msys-2.0.dll linkage), GPL3
  summary: Utilities to work with and produce manuals, ASCII text, and on-line documentation
    from a single source file
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/msys/i686/info-6.0-1-i686.pkg.tar.xz
      md5: 65025a00be7196c680f41001cf55cee7
      mv-src: '*'
      mv-dst: Library/
    win-64:
      url: http://repo.msys2.org/msys/x86_64/info-6.0-1-x86_64.pkg.tar.xz
      md5: 5de816053f1cd0a9bb2aff164539ffab
      mv-src: '*'
      mv-dst: Library/
