package:
  name: m2-msys2-pkgfile
  version: '15'
source:
  url: http://repo.msys2.org/msys/sources/pkgfile-15-1.src.tar.gz
  md5: baadc0debaadc0debaadc0debaadc0de
build:
  number: '1'
requirements:
  run:
  - m2-msys2-libarchive
  - m2-msys2-curl
  - m2-msys2-pcre
  - m2-msys2-pacman
about:
  home: http://github.com/falconindy/pkgfile
  license: GPL (msys-2.0.dll linkage), MIT
  summary: A pacman .files metadata explorer
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/msys/i686/pkgfile-15-1-i686.pkg.tar.xz
      md5: 68bac64562efb056fc9d63ccbc8cbb5d
      mv-src: '*'
      mv-dst: Library/
    win-64:
      url: http://repo.msys2.org/msys/x86_64/pkgfile-15-1-x86_64.pkg.tar.xz
      md5: 36107c59bee89372fd770d93a5213622
      mv-src: '*'
      mv-dst: Library/
