{% set posix = 'm2-msys2-' if win else '' %}
{% set native = 'm2-mingw-w64-' if win else '' %}

package:
  name: r-lubridate
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "1.5.0"

source:
  fn: lubridate_1.5.0.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/lubridate_1.5.0.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/lubridate/lubridate_1.5.0.tar.gz


  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat, knitr
requirements:
  build:
    - r-base
    - r-stringr
    - {{posix}}base       # [win]
    - {{posix}}zip        # [win]
    - {{native}}toolchain # [win]
    - gcc                 # [not win]

  run:
    - r-base
    - r-stringr

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('lubridate')" # [not win]
    - "\"%R%\" -e \"library('lubridate')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  #home:
  license: GPL
  summary: 'Functions to work with date-times and timespans: fast and user friendly parsing of
    date-time data, extraction and updating of components of a date-time (years, months,
    days, hours, minutes, and seconds), algebraic manipulation on date-time and timespan
    objects. The ''lubridate'' package has a consistent and memorable syntax that makes
    working with dates easy and fun.'

  license_family: GPL3

# The original CRAN metadata for this package was:

# Package: lubridate
# Maintainer: Vitalie Spinu <spinuvit@gmail.com>
# License: GPL
# Title: Make Dealing with Dates a Little Easier
# LazyData: true
# Type: Package
# Authors@R: c(person("Garrett", "Grolemund", role = "aut"), person("Vitalie", "Spinu", email = "spinuvit@gmail.com", role = c("aut","cre")), person("Hadley", "Wickham", role = "aut"), person("Jan", "Lyttle", role="ctb"), person("Imanuel", "Constigan", role = "ctb"), person("Jason", "Law", role="ctb"), person("Doug","Mitarotonda", role="ctb"), person("Joseph", "Larmarange", role="ctb"), person("Jonathan", "Boiser", role="ctb"), person("Chel Hee", "Lee", role = "ctb"))
# Description: Functions to work with date-times and timespans: fast and user friendly parsing of date-time data, extraction and updating of components of a date-time (years, months, days, hours, minutes, and seconds), algebraic manipulation on date-time and timespan objects. The 'lubridate' package has a consistent and memorable syntax that makes working with dates easy and fun.
# Enhances: chron, timeDate, zoo, xts, its, tis, timeSeries, fts, tseries
# Version: 1.5.0
# Depends: methods, R (>= 3.0.0)
# Imports: stringr
# Suggests: testthat, knitr
# BugReports: https://github.com/hadley/lubridate/issues
# VignetteBuilder: knitr
# Collate: 'Dates.r' 'POSIXt.r' 'timespans.r' 'intervals.r' 'difftimes.r' 'durations.r' 'util.r' 'periods.r' 'accessors-day.r' 'accessors-dst.r' 'accessors-hour.r' 'accessors-minute.r' 'accessors-month.r' 'accessors-quarter.r' 'accessors-second.r' 'accessors-tz.r' 'accessors-week.r' 'accessors-year.r' 'am-pm.r' 'time-zones.r' 'numeric.r' 'coercion.r' 'constants.r' 'data.r' 'decimal-dates.r' 'deprecated.r' 'epochs.r' 'guess.r' 'help.r' 'instants.r' 'leap-years.r' 'ops-addition.r' 'ops-%m+%.r' 'ops-division.r' 'ops-integer-division.r' 'ops-modulo.r' 'ops-multiplication.r' 'ops-subtraction.r' 'parse.r' 'pretty.r' 'round.r' 'stamp.r' 'update.r'
# RoxygenNote: 5.0.1
# NeedsCompilation: yes
# Packaged: 2015-12-02 14:38:44 UTC; vspinu
# Author: Garrett Grolemund [aut], Vitalie Spinu [aut, cre], Hadley Wickham [aut], Jan Lyttle [ctb], Imanuel Constigan [ctb], Jason Law [ctb], Doug Mitarotonda [ctb], Joseph Larmarange [ctb], Jonathan Boiser [ctb], Chel Hee Lee [ctb]
# Repository: CRAN
# Date/Publication: 2015-12-03 00:25:12

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
