package:
  name: m2-msys2-automake1.9
  version: 1.9.6
source:
  url: http://repo.msys2.org/msys/sources/automake1.9-1.9.6-2.src.tar.gz
  md5: baadc0debaadc0debaadc0debaadc0de
build:
  number: '2'
requirements:
  run:
  - m2-msys2-perl
  - m2-msys2-bash
about:
  home: http://www.gnu.org/software/automake
  license: GPL
  summary: A GNU tool for automatically creating Makefiles
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/msys/i686/automake1.9-1.9.6-2-any.pkg.tar.xz
      md5: 2e7695beceba4bd101a3d75679328def
      mv-src: '*'
      mv-dst: Library/
    win-64:
      url: http://repo.msys2.org/msys/x86_64/automake1.9-1.9.6-2-any.pkg.tar.xz
      md5: f225464f89487e587aadb4df41d1becc
      mv-src: '*'
      mv-dst: Library/
