{% set pfx = 'm2-mingw-w64-' %} [win]

package:
  name: r # [win]
  name: r-base # [not win]
  version: 3.2.4

source:
  fn: R-3.2.4-revised.tar.gz
  url: http://cran.cnr.berkeley.edu/src/base/R-3/R-3.2.4-revised.tar.gz
  sha1: 54d8b02b4564655f1be84b4a830813f8452b5e9c
  patches:
    - share-make-vars.mk.patch
    - mac-unicode.patch # [osx]
    - 0001-Win32-Stop-confusing-PECOFF_SHLIBS-with-CYGWIN_BUILD.patch
    - 0002-Win32-Fix-trio-config-h-include-depth-issue.patch
    - 0003-Win32-Do-not-static-libgcc-link.patch              # This patch is only correct if using MSYS2's tcltk.
    - 0004-Win32-Use-TCL_VERSION_86.patch                     # This patch is only correct if using MSYS2's tcltk.
    - 0005-Win32-Extend-sqrt-NA_real_-hack-to-all-GCC-versions.patch

build:
  rpaths:
    - lib/R/lib/
    - lib/
  detect_binary_files_with_prefix: true

requirements:
  build:
    - m2-msys2-base        # [win]
    - m2-msys2-texinfo-tex # [win]
    - m2-msys2-texinfo     # [win]
    - m2-msys2-curl        # [win]
    - m2-msys2-zip         # [win]
    - m2-msys2-unzip       # [win]
    - m2-msys2-p7zip       # [win]
    - m2-msys2-tar         # [win]
    - readline             # [not win]
    - ncurses              # [not win]
    - cairo                # [linux]
    - pango                # [linux]
    - gcc                  # [not win]
    - jpeg                 # [not win]
    - {{pfx}}libjpeg-turbo # [win]
    - {{pfx}}toolchain     # [win]
    - {{pfx}}bzip2         # [win]
    - {{pfx}}libiconv      # [win]
    - {{pfx}}fftw          # [win]
    - {{pfx}}gmp           # [win]
    - {{pfx}}fftw          # [win]
    - {{pfx}}xz            # [win]
    - {{pfx}}mpfr          # [win]
    - {{pfx}}libsndfile    # [win]
    - {{pfx}}bwidget       # [win]
    - {{pfx}}tktable       # [win]
    - {{pfx}}tk            # [win]
    - tk                   # [not win]
    - {{pfx}}zlib
    - {{pfx}}gsl
    - {{pfx}}libpng
    - {{pfx}}libtiff
    - {{pfx}}libxml2
    - {{pfx}}pcre

  run:
    - readline             # [not win]
    - ncurses              # [not win]
    - cairo                # [linux]
    - pango                # [linux]
    - {{pfx}}libgcc
    - jpeg                 # [not win]
    - {{pfx}}libjpeg-turbo # [win]
    - {{pfx}}toolchain     # [win]
    - {{pfx}}bzip2         # [win]
    - {{pfx}}libiconv      # [win]
    - {{pfx}}fftw          # [win]
    - {{pfx}}gmp           # [win]
    - {{pfx}}fftw          # [win]
    - {{pfx}}xz            # [win]
    - {{pfx}}mpfr          # [win]
    - {{pfx}}sndfile       # [win]
    - {{pfx}}bwidget       # [win]
    - {{pfx}}tktable       # [win]
    - {{pfx}}tk            # [win]
    - tk                   # [not win]
    - {{pfx}}zlib
    - {{pfx}}gsl
    - {{pfx}}libpng
    - {{pfx}}libtiff
    - {{pfx}}libxml2
    - {{pfx}}pcre

test:
  commands:
    - R -h
    - R --version
    - Rscript --version
    - Rscript -e  'cat("ok\\n")'
    - open # [win]
    # There doesn't seem to be a way to test this one
    # - RSetReg # [win]
    - Rfe --help # [win]
    - Rterm --help # [win]
    - Rterm --version # [win]

about:
  home: http://www.r-project.org/
  license: GPL
