{% set pfx = 'm2-mingw-w64-' %} [win]

package:
  name: r # [win]
  name: r-base # [not win]
  version: 3.2.2

source:
  fn: R-3.2.2.tar.gz
  url: http://cran.cnr.berkeley.edu/src/base/R-3/R-3.2.2.tar.gz
  sha1: 68c74db1c5a2f2040280a03b8396e4d28a5a7617
  patches:
    - share-make-vars.mk.patch
    - mac-unicode.patch # [osx]
    - 0001-Win32-Stop-confusing-PECOFF_SHLIBS-with-CYGWIN_BUILD.patch
    - 0002-Win32-Fix-trio-config-h-include-depth-issue.patch
    - 0003-Win32-Do-not-static-libgcc-link.patch
    - 0004-Win32-Use-TCL_VERSION_86.patch

build:
  rpaths:
    - lib/R/lib/
    - lib/
  detect_binary_files_with_prefix: true

requirements:
  build:
    - m2-msys2-base        # [win]
    - m2-msys2-texinfo-tex # [win]
    - readline             # [not win]
    - ncurses              # [not win]
    - cairo                # [linux]
    - pango                # [linux]
    - gcc                  # [not win]
    - jpeg                 # [not win]
    - {{pfx}}libjpeg-turbo # [win]
    - {{pfx}}toolchain     # [win]
    - {{pfx}}bzip2         # [win]
    - {{pfx}}libiconv      # [win]
    - {{pfx}}fftw          # [win]
    - {{pfx}}gmp           # [win]
    - {{pfx}}fftw          # [win]
    - {{pfx}}xz            # [win]
    - {{pfx}}mpfr          # [win]
    - {{pfx}}libsndfile    # [win]
    - {{pfx}}tk
    - {{pfx}}zlib
    - {{pfx}}gsl
    - {{pfx}}libpng
    - {{pfx}}libtiff
    - {{pfx}}libxml2
    - {{pfx}}pcre

  run:
    - readline             # [not win]
    - ncurses              # [not win]
    - tk                   # [not win]
    - cairo                # [linux]
    - pango                # [linux]
    - {{pfx}}libgcc
    - jpeg                 # [not win]
    - {{pfx}}libjpeg-turbo # [win]
    - {{pfx}}toolchain     # [win]
    - {{pfx}}bzip2         # [win]
    - {{pfx}}libiconv      # [win]
    - {{pfx}}fftw          # [win]
    - {{pfx}}gmp           # [win]
    - {{pfx}}fftw          # [win]
    - {{pfx}}xz            # [win]
    - {{pfx}}mpfr          # [win]
    - {{pfx}}sndfile       # [win]
    - {{pfx}}tk
    - {{pfx}}zlib
    - {{pfx}}gsl
    - {{pfx}}libpng
    - {{pfx}}libtiff
    - {{pfx}}libxml2
    - {{pfx}}pcre

test:
  commands:
    - R -h
    - R --version
    - Rscript --version
    - Rscript -e  'cat("ok\\n")'
    - open # [win]
    # There doesn't seem to be a way to test this one
    # - RSetReg # [win]
    - Rfe --help # [win]
    - Rterm --help # [win]
    - Rterm --version # [win]

about:
  home: http://www.r-project.org/
  license: GPL
