package:
  name: m2-msys2-perl-io-socket-ssl
  version: '2.016'
source:
  url: http://repo.msys2.org/msys/sources/perl-IO-Socket-SSL-2.016-1.src.tar.gz
  md5: 936524317a13f7da01ff4676bdb271e2
build:
  number: '1'
requirements:
  run:
  - m2-msys2-perl-net-ssleay
  - m2-msys2-perl
  - m2-msys2-perl-uri
about:
  home: http://search.cpan.org/dist/IO-Socket-SSL/
  license: GPL, PerlArtistic
  summary: Nearly transparent SSL encapsulation for IO::Socket::INET
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/msys/i686/perl-IO-Socket-SSL-2.016-1-any.pkg.tar.xz
      md5: c128aed19387f5096d49449909136f3a
      mv-src: '*'
      mv-dst: Library/
    win-64:
      url: http://repo.msys2.org/msys/x86_64/perl-IO-Socket-SSL-2.016-1-any.pkg.tar.xz
      md5: 7d6922263168714570dd239047a8e7b5
      mv-src: '*'
      mv-dst: Library/
