package:
  name: m2-mingw-w64-speex
  version: 1.2rc2
source:
  url: http://repo.msys2.org/mingw/sources/mingw-w64-speex-1.2rc2-2.src.tar.gz
  md5: 936524317a13f7da01ff4676bdb271e2
build:
  number: '2'
requirements:
  run:
  - m2-mingw-w64-libogg
  - m2-mingw-w64-speexdsp
about:
  home: http://www.speex.org/
  license: BSD
  summary: A free codec for free speech (mingw-w64)
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/mingw/i686/mingw-w64-i686-speex-1.2rc2-2-any.pkg.tar.xz
      md5: 0ce8d9a649d2322f0fd38fe4d9f9d15b
      mv-src: mingw32
      mv-dst: Library/mingw-w64
    win-64:
      url: http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-speex-1.2rc2-2-any.pkg.tar.xz
      md5: 63fe26c97ed30310f7c296724bcb6da4
      mv-src: mingw64
      mv-dst: Library/mingw-w64
