package:
  name: m2-mingw-w64-openssl
  version: 1.0.2.g
source:
  url: http://repo.msys2.org/mingw/sources/mingw-w64-openssl-1.0.2.g-1.src.tar.gz
  md5: b716088c5b5b0ef6a5b41249c5e1f28c
build:
  number: '1'
requirements:
  run:
  - m2-mingw-w64-ca-certificates
  - m2-mingw-w64-gcc-libs
  - m2-mingw-w64-zlib
about:
  home: https://www.openssl.org
  license: BSD
  summary: The Open Source toolkit for Secure Sockets Layer and Transport Layer Security
    (mingw-w64)
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/mingw/i686/mingw-w64-i686-openssl-1.0.2.g-1-any.pkg.tar.xz
      md5: 9c013fe9eb7e545bed603e4cc601a38d
      mv-src: mingw32
      mv-dst: Library/mingw-w64
    win-64:
      url: http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-openssl-1.0.2.g-1-any.pkg.tar.xz
      md5: 357cd00498eba308652aae5ed71e7a0c
      mv-src: mingw64
      mv-dst: Library/mingw-w64
