package:
  name: m2-msys2-perl-html-tagset
  version: '3.20'
source:
  url: http://repo.msys2.org/msys/sources/perl-HTML-Tagset-3.20-2.src.tar.gz
  md5: 936524317a13f7da01ff4676bdb271e2
build:
  number: '2'
requirements:
  run:
  - m2-msys2-perl
about:
  home: http://search.cpan.org/dist/HTML-Tagset/
  license: GPL, PerlArtistic
  summary: Data tables useful in parsing HTML
extra:
  msys2-binaries:
    win-32:
      srcpkg: msys/perl-HTML-Tagset
      url: http://repo.msys2.org/msys/i686/perl-HTML-Tagset-3.20-2-any.pkg.tar.xz
      md5: 810e3e2a45a9997d1562914e34e58573
      mv-src: '*'
      mv-dst: Library/
    win-64:
      srcpkg: msys/perl-HTML-Tagset
      url: http://repo.msys2.org/msys/x86_64/perl-HTML-Tagset-3.20-2-any.pkg.tar.xz
      md5: 2d736a4ec35e749603a7854144ddfb74
      mv-src: '*'
      mv-dst: Library/
