package:
  name: m2-mingw-w64-zlib
  version: 1.2.8
source:
  url: http://repo.msys2.org/mingw/sources/mingw-w64-zlib-1.2.8-9.src.tar.gz
  md5: 32078e2a67e34ff6c0b1795fe6ed9d36
build:
  number: '9'
requirements:
  run:
  - m2-mingw-w64-bzip2
about:
  home: http://www.zlib.net/
  license: ZLIB
  summary: Compression library implementing the deflate compression method found in
    gzip and PKZIP (mingw-w64)
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/mingw/i686/mingw-w64-i686-zlib-1.2.8-9-any.pkg.tar.xz
      md5: 87c65e9b2930436a75dfd7d459ae98cb
      mv-src: mingw32
      mv-dst: Library/mingw-w64
    win-64:
      url: http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-zlib-1.2.8-9-any.pkg.tar.xz
      md5: 60c3a388478f411b7a0908441ebeb537
      mv-src: mingw64
      mv-dst: Library/mingw-w64
