package:
  name: m2-msys2-openssl
  version: 1.0.2.g
source:
  url: http://repo.msys2.org/msys/sources/openssl-1.0.2.g-1.src.tar.gz
  md5: 502c8853c85a04451c1ea2283868b600
build:
  number: '1'
requirements:
  run:
  - m2-msys2-libopenssl
  - m2-msys2-zlib
about:
  home: https://www.openssl.org
  license: GPL (msys-2.0.dll linkage), custom:BSD
  summary: The Open Source toolkit for Secure Sockets Layer and Transport Layer Security
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/msys/i686/openssl-1.0.2.g-1-i686.pkg.tar.xz
      md5: 737f7b0335571846fa7bdcf1566328e6
      mv-src: '*'
      mv-dst: Library/
    win-64:
      url: http://repo.msys2.org/msys/x86_64/openssl-1.0.2.g-1-x86_64.pkg.tar.xz
      md5: f21d4da1fa35140029905b664e7bca7f
      mv-src: '*'
      mv-dst: Library/
