package:
  name: m2-msys2-autogen
  version: 5.18.4
source:
  url: http://repo.msys2.org/msys/sources/autogen-5.18.4-2.src.tar.gz
  md5: baadc0debaadc0debaadc0debaadc0de
build:
  number: '2'
requirements:
  run:
  - m2-msys2-gcc-libs
  - m2-msys2-gmp
  - m2-msys2-libcrypt
  - m2-msys2-libffi
  - m2-msys2-libgc
  - m2-msys2-libguile
  - m2-msys2-libxml2
about:
  home: http://autogen.sourceforge.net/
  license: GPL (msys-2.0.dll linkage), GPL3
  summary: A tool designed to simplify the creation and maintenance of programs that
    contain large amounts of repetitious text
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/msys/i686/autogen-5.18.4-2-i686.pkg.tar.xz
      md5: 3a2e91fb338ebc61c60be44735c6933c
      mv-src: '*'
      mv-dst: Library/
    win-64:
      url: http://repo.msys2.org/msys/x86_64/autogen-5.18.4-2-x86_64.pkg.tar.xz
      md5: 19cab152bb2aaab23e15899bfd19ef55
      mv-src: '*'
      mv-dst: Library/
