package:
  name: m2-msys2-gettext-devel
  version: 0.19.7
source:
  url: http://repo.msys2.org/msys/sources/gettext-devel-0.19.7-3.src.tar.gz
  md5: baadc0debaadc0debaadc0debaadc0de
build:
  number: '3'
requirements:
  run:
  - m2-msys2-gettext
  - m2-msys2-libiconv-devel
about:
  home: https://www.gnu.org/software/gettext/
  license: GPL
  summary: GNU Internationalization development utilities
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/msys/i686/gettext-devel-0.19.7-3-i686.pkg.tar.xz
      md5: bf3d0b9c8ac53ec24d200b6ef0467766
      mv-src: '*'
      mv-dst: Library/
    win-64:
      url: http://repo.msys2.org/msys/x86_64/gettext-devel-0.19.7-3-x86_64.pkg.tar.xz
      md5: b09d1a04e85650cd28f8dfa0ee5906cb
      mv-src: '*'
      mv-dst: Library/
