package:
  name: m2-msys2-pcre
  version: '8.38'
source:
  url: http://repo.msys2.org/msys/sources/pcre-8.38-1.src.tar.gz
  md5: b02505586bcd667b6031f2ea67a7a4a4
build:
  number: '1'
requirements:
  run:
  - m2-msys2-libreadline
  - m2-msys2-libbz2
  - m2-msys2-zlib
  - m2-msys2-libpcre
  - m2-msys2-libpcre16
  - m2-msys2-libpcre32
  - m2-msys2-libpcrecpp
  - m2-msys2-libpcreposix
about:
  home: http://www.pcre.org/
  license: GPL (msys-2.0.dll linkage), BSD
  summary: A library that implements Perl 5-style regular expressions
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/msys/i686/pcre-8.38-1-i686.pkg.tar.xz
      md5: 85d102da40fd75f86e69d0a834bc05c2
      mv-src: '*'
      mv-dst: Library/
    win-64:
      url: http://repo.msys2.org/msys/x86_64/pcre-8.38-1-x86_64.pkg.tar.xz
      md5: 9c2df12f1fe4fd8e4993d0ee40ab3b9b
      mv-src: '*'
      mv-dst: Library/
