package:
  name: m2-mingw-w64-gcc-libgfortran
  version: 5.3.0
source:
  url: http://repo.msys2.org/mingw/sources/mingw-w64-gcc-libgfortran-5.3.0-2.src.tar.gz
  md5: baadc0debaadc0debaadc0debaadc0de
build:
  number: '2'
requirements:
  run:
  - m2-mingw-w64-gcc-libs
about:
  home: http://gcc.gnu.org
  license: GPL, LGPL, FDL, custom
  summary: GNU Compiler Collection (libgfortran) for MinGW-w64
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/mingw/i686/mingw-w64-i686-gcc-libgfortran-5.3.0-2-any.pkg.tar.xz
      md5: 03b0111cf0c50ed1d3eda0ee3e67e589
      mv-src: mingw32
      mv-dst: Library/mingw-w64
    win-64:
      url: http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-gcc-libgfortran-5.3.0-2-any.pkg.tar.xz
      md5: 587cfdb8cef6467d8ebcfe459a017136
      mv-src: mingw64
      mv-dst: Library/mingw-w64
