package:
  name: m2-msys2-libgpg-error
  version: '1.21'
source:
  url: http://repo.msys2.org/msys/sources/libgpg-error-1.21-1.src.tar.gz
  md5: 93c881e36db836a85380f4b89c4bb6fe
build:
  number: '1'
requirements:
  run:
  - m2-msys2-msys2-runtime
  - m2-msys2-bash
  - m2-msys2-libiconv
  - m2-msys2-libintl
about:
  home: http://www.gnupg.org
  license: GPL (msys-2.0.dll linkage), LGPL
  summary: Support library for libgcrypt
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/msys/i686/libgpg-error-1.21-1-i686.pkg.tar.xz
      md5: 624acd8659229ed56ca75c098dffc423
      mv-src: '*'
      mv-dst: Library/
    win-64:
      url: http://repo.msys2.org/msys/x86_64/libgpg-error-1.21-1-x86_64.pkg.tar.xz
      md5: d11a28ac0347530fc41acc7d28e23ece
      mv-src: '*'
      mv-dst: Library/
