package:
  name: m2-msys2-perl-encode-locale
  version: '1.04'
source:
  url: http://repo.msys2.org/msys/sources/perl-Encode-Locale-1.04-1.src.tar.gz
  md5: 936524317a13f7da01ff4676bdb271e2
build:
  number: '1'
requirements:
  run:
  - m2-msys2-perl
about:
  home: http://search.cpan.org/dist/Encode-Locale
  license: PerlArtistic, GPL
  summary: Determine the locale encoding
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/msys/i686/perl-Encode-Locale-1.04-1-any.pkg.tar.xz
      md5: db955b95d1ebf2f2597ba3097c96e126
      mv-src: '*'
      mv-dst: Library/
    win-64:
      url: http://repo.msys2.org/msys/x86_64/perl-Encode-Locale-1.04-1-any.pkg.tar.xz
      md5: 8b85775f64ab0ab320ad19fae9fe869c
      mv-src: '*'
      mv-dst: Library/
