package:
  name: m2-msys2-gmp
  version: 6.1.0
source:
  url: http://repo.msys2.org/msys/sources/gmp-6.1.0-2.src.tar.gz
  md5: 53dcd1895949b977ff0a5374364abf66
build:
  number: '2'
requirements:
  run: []
about:
  home: https://gmplib.org/
  license: GPL, LGPL3
  summary: A free library for arbitrary precision arithmetic
extra:
  msys2-binaries:
    win-32:
      srcpkg: msys/gmp
      url: http://repo.msys2.org/msys/i686/gmp-6.1.0-2-i686.pkg.tar.xz
      md5: c281717b431f0431f3fb5f9f9e1611d2
      mv-src: '*'
      mv-dst: Library/
    win-64:
      srcpkg: msys/gmp
      url: http://repo.msys2.org/msys/x86_64/gmp-6.1.0-2-x86_64.pkg.tar.xz
      md5: 2f61e08e7ac091759bfa59236e2e98db
      mv-src: '*'
      mv-dst: Library/
