package:
  name: m2-mingw-w64-ca-certificates
  version: '20150426'
source:
  url: http://repo.msys2.org/mingw/sources/mingw-w64-ca-certificates-20150426-2.src.tar.gz
  md5: 936524317a13f7da01ff4676bdb271e2
build:
  number: '2'
requirements:
  run:
  - m2-mingw-w64-p11-kit
about:
  home: http://packages.qa.debian.org/c/ca-certificates.html
  license: MPL, GPL
  summary: Common CA certificates (mingw-w64)
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/mingw/i686/mingw-w64-i686-ca-certificates-20150426-2-any.pkg.tar.xz
      md5: dfb4c99f56152bc8242e5e330be4251a
      mv-src: mingw32
      mv-dst: Library/mingw-w64
    win-64:
      url: http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-ca-certificates-20150426-2-any.pkg.tar.xz
      md5: 126676c0109e8ea3a798a3dc904dab06
      mv-src: mingw64
      mv-dst: Library/mingw-w64
