package:
  name: m2-msys2-automake-wrapper
  version: '10'
source:
  url: http://repo.msys2.org/msys/sources/automake-wrapper-10-1.src.tar.gz
  md5: baadc0debaadc0debaadc0debaadc0de
build:
  number: '1'
requirements:
  run:
  - m2-msys2-bash
  - m2-msys2-gawk
  - m2-msys2-automake1.6
  - m2-msys2-automake1.7
  - m2-msys2-automake1.7
  - m2-msys2-automake1.8
  - m2-msys2-automake1.9
  - m2-msys2-automake1.10
  - m2-msys2-automake1.11
  - m2-msys2-automake1.12
  - m2-msys2-automake1.13
  - m2-msys2-automake1.14
  - m2-msys2-automake1.15
about:
  home: http://www.gentoo.org
  license: GPL
  summary: Wrapper scripts for automake and aclocal
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/msys/i686/automake-wrapper-10-1-any.pkg.tar.xz
      md5: b76ce20b712be6c257d04d7c43a1e320
      mv-src: '*'
      mv-dst: Library/
    win-64:
      url: http://repo.msys2.org/msys/x86_64/automake-wrapper-10-1-any.pkg.tar.xz
      md5: a5d33ca358269592e7eb36f68076b196
      mv-src: '*'
      mv-dst: Library/
