package:
  name: m2-msys2-make
  version: '4.1'
source:
  url: http://repo.msys2.org/msys/sources/make-4.1-4.src.tar.gz
  md5: 936524317a13f7da01ff4676bdb271e2
build:
  number: '4'
requirements:
  run:
  - m2-msys2-msys2-runtime
  - m2-msys2-libintl
  - m2-msys2-bash
about:
  home: http://www.gnu.org/software/make
  license: GPL, GPL3
  summary: GNU make utility to maintain groups of programs
extra:
  msys2-binaries:
    win-32:
      srcpkg: msys/make
      url: http://repo.msys2.org/msys/i686/make-4.1-4-i686.pkg.tar.xz
      md5: abda511b40d53049b4f9ba7433033932
      mv-src: '*'
      mv-dst: Library/
    win-64:
      srcpkg: msys/make
      url: http://repo.msys2.org/msys/x86_64/make-4.1-4-x86_64.pkg.tar.xz
      md5: 7467f54b8cb57c47ff0b2c5f6d9c97af
      mv-src: '*'
      mv-dst: Library/
