package:
  name: m2-msys2-libsqlite
  version: 3.10.0.0
source:
  url: http://repo.msys2.org/msys/sources/libsqlite-3.10.0.0-1.src.tar.gz
  md5: baadc0debaadc0debaadc0debaadc0de
build:
  number: '1'
requirements:
  run:
  - m2-msys2-libreadline
  - m2-msys2-icu
  - m2-msys2-zlib
about:
  home: http://www.sqlite.org/
  license: GPL (msys-2.0.dll linkage), PublicDomain
  summary: Sqlite3 library
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/msys/i686/libsqlite-3.10.0.0-1-i686.pkg.tar.xz
      md5: 829cb8a02b30ee759c3baf958600095e
      mv-src: '*'
      mv-dst: Library/
    win-64:
      url: http://repo.msys2.org/msys/x86_64/libsqlite-3.10.0.0-1-x86_64.pkg.tar.xz
      md5: 6d9195c375a5d5ce7ab0ca2faa72ccd0
      mv-src: '*'
      mv-dst: Library/
