package:
  name: m2-mingw-w64-crt-git
  version: 5.0.0.4627.03684c4
source:
  url: http://repo.msys2.org/mingw/sources/mingw-w64-crt-git-5.0.0.4627.03684c4-1.src.tar.gz
  md5: baadc0debaadc0debaadc0debaadc0de
build:
  number: '1'
requirements:
  run:
  - m2-mingw-w64-headers-git
about:
  home: http://mingw-w64.sourceforge.net
  license: custom
  summary: MinGW-w64 CRT for Windows
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/mingw/i686/mingw-w64-i686-crt-git-5.0.0.4627.d55f21d-1-any.pkg.tar.xz
      md5: 792817e39252a19a766a224c7b3c819c
      mv-src: mingw32
      mv-dst: Library/mingw-w64
    win-64:
      url: http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-crt-git-5.0.0.4627.03684c4-1-any.pkg.tar.xz
      md5: f02843063845c72e36f7b66079793255
      mv-src: mingw64
      mv-dst: Library/mingw-w64
