package:
  name: m2-mingw-w64-libpng
  version: 1.6.21
source:
  url: http://repo.msys2.org/mingw/sources/mingw-w64-libpng-1.6.21-1.src.tar.gz
  md5: 6ed6079d1d6b1d253cd967a58d2e368f
build:
  number: '1'
requirements:
  run:
  - m2-mingw-w64-gcc-libs
  - m2-mingw-w64-zlib
about:
  home: http://www.libpng.org/pub/png/libpng.html
  license: custom
  summary: A collection of routines used to create PNG format graphics (mingw-w64)
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/mingw/i686/mingw-w64-i686-libpng-1.6.21-1-any.pkg.tar.xz
      md5: 4bee6ac6e0e7e67dc57d448cb7f26dfc
      mv-src: mingw32
      mv-dst: Library/mingw-w64
    win-64:
      url: http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-libpng-1.6.21-1-any.pkg.tar.xz
      md5: fc72521c22ecd35f4d2e48b4afa36cd5
      mv-src: mingw64
      mv-dst: Library/mingw-w64
