package:
  name: m2-msys2-libutil-linux
  version: 2.26.2
source:
  url: http://repo.msys2.org/msys/sources/libutil-linux-2.26.2-1.src.tar.gz
  md5: baadc0debaadc0debaadc0debaadc0de
build:
  number: '1'
requirements:
  run:
  - m2-msys2-gcc-libs
  - m2-msys2-libintl
  - m2-msys2-msys2-runtime
about:
  home: http://www.kernel.org/pub/linux/utils/util-linux/
  license: GPL (msys-2.0.dll linkage), GPL3
  summary: Block device ID and Universally Unique ID libraries
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/msys/i686/libutil-linux-2.26.2-1-i686.pkg.tar.xz
      md5: 60451d51f468c4f1ae05e5f342e2809b
      mv-src: '*'
      mv-dst: Library/
    win-64:
      url: http://repo.msys2.org/msys/x86_64/libutil-linux-2.26.2-1-x86_64.pkg.tar.xz
      md5: c923605dfb8d73ffbbfab377bf4c3ed5
      mv-src: '*'
      mv-dst: Library/
