package:
  name: m2-msys2-texinfo
  version: '6.0'
source:
  url: http://repo.msys2.org/msys/sources/texinfo-6.0-1.src.tar.gz
  md5: baadc0debaadc0debaadc0debaadc0de
build:
  number: '1'
requirements:
  run:
  - m2-msys2-info
  - m2-msys2-perl
  - m2-msys2-bash
about:
  home: http://www.gnu.org/software/texinfo/
  license: GPL (msys-2.0.dll linkage), GPL3
  summary: Utilities to work with and produce manuals, ASCII text, and on-line documentation
    from a single source file
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/msys/i686/texinfo-6.0-1-i686.pkg.tar.xz
      md5: 8afd6952a749f996c525aff18fd06a77
      mv-src: '*'
      mv-dst: Library/
    win-64:
      url: http://repo.msys2.org/msys/x86_64/texinfo-6.0-1-x86_64.pkg.tar.xz
      md5: 8e6d6b7acad68aad9940c987745c08ab
      mv-src: '*'
      mv-dst: Library/
