package:
  name: m2-msys2-perl
  version: 5.22.1
source:
  url: http://repo.msys2.org/msys/sources/perl-5.22.1-1.src.tar.gz
  md5: e44e7726b1152dfe836e2396cbcbcdac
build:
  number: '1'
requirements:
  run:
  - m2-msys2-db
  - m2-msys2-gdbm
  - m2-msys2-libcrypt
  - m2-msys2-coreutils
  - m2-msys2-msys2-runtime
  - m2-msys2-bash
about:
  home: http://www.perl.org
  license: GPL, PerlArtistic
  summary: A highly capable, feature-rich programming language
extra:
  msys2-binaries:
    win-32:
      srcpkg: msys/perl
      url: http://repo.msys2.org/msys/i686/perl-5.22.1-1-i686.pkg.tar.xz
      md5: 72efc983e009fc138198e797a7df6bd3
      mv-src: '*'
      mv-dst: Library/
    win-64:
      srcpkg: msys/perl
      url: http://repo.msys2.org/msys/x86_64/perl-5.22.1-1-x86_64.pkg.tar.xz
      md5: 194672a9450198d2b6b7cd8f8a2f5593
      mv-src: '*'
      mv-dst: Library/
