package:
  name: m2-msys2-groff
  version: 1.22.3
source:
  url: http://repo.msys2.org/msys/sources/groff-1.22.3-1.src.tar.gz
  md5: baadc0debaadc0debaadc0debaadc0de
build:
  number: '1'
requirements:
  run:
  - m2-msys2-perl
  - m2-msys2-gcc-libs
about:
  home: http://www.gnu.org/software/groff/groff.html
  license: GPL
  summary: GNU troff text-formatting system
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/msys/i686/groff-1.22.3-1-i686.pkg.tar.xz
      md5: d411f9fc7a70c69b12681ca316278efb
      mv-src: '*'
      mv-dst: Library/
    win-64:
      url: http://repo.msys2.org/msys/x86_64/groff-1.22.3-1-x86_64.pkg.tar.xz
      md5: 7369f097806658403af2cdc7a5eac359
      mv-src: '*'
      mv-dst: Library/
