package:
  name: m2-mingw-w64-libffi
  version: 3.2.1
source:
  url: http://repo.msys2.org/mingw/sources/mingw-w64-libffi-3.2.1-3.src.tar.gz
  md5: 936524317a13f7da01ff4676bdb271e2
build:
  number: '3'
requirements:
  run: []
about:
  home: http://sourceware.org/libffi
  license: MIT
  summary: A portable, high level programming interface to various calling conventions
    (mingw-w64)
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/mingw/i686/mingw-w64-i686-libffi-3.2.1-3-any.pkg.tar.xz
      md5: 9c74fec83fd6eb5a3a777e99eae0f5f9
      mv-src: mingw32
      mv-dst: Library/mingw-w64
    win-64:
      url: http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-libffi-3.2.1-3-any.pkg.tar.xz
      md5: 23925748d6a28bffb1a4707f954ee10d
      mv-src: mingw64
      mv-dst: Library/mingw-w64
