package:
  name: m2-mingw-w64-nlopt
  version: 2.4.2
source:
  url: http://repo.msys2.org/mingw/sources/mingw-w64-nlopt-2.4.2-2.src.tar.gz
  md5: baadc0debaadc0debaadc0debaadc0de
build:
  number: '2'
requirements:
  run: []
about:
  home: http://ab-initio.mit.edu/wiki/index.php/NLopt
  license: LGPLv2.1+
  summary: A library for nonlinear optimization (mingw-w64)
extra:
  msys2-binaries:
    win-32:
      url: file://C:/Users/builder/repo/mingw/i686/mingw-w64-i686-nlopt-2.4.2-2-any.pkg.tar.xz
      md5: cef3ea6e2dd635c350cc23d4131c84f2
      mv-src: mingw32
      mv-dst: Library/mingw-w64
    win-64:
      url: file://C:/Users/builder/repo/mingw/x86_64/mingw-w64-x86_64-nlopt-2.4.2-2-any.pkg.tar.xz
      md5: d41d8cd98f00b204e9800998ecf8427e
      mv-src: mingw64
      mv-dst: Library/mingw-w64
