package:
  name: m2-msys2-libreadline
  version: 6.3.008
source:
  url: http://repo.msys2.org/msys/sources/libreadline-6.3.008-7.src.tar.gz
  md5: baadc0debaadc0debaadc0debaadc0de
build:
  number: '7'
requirements:
  run:
  - m2-msys2-ncurses
about:
  home: http://tiswww.case.edu/php/chet/readline/rltop.html
  license: GPL
  summary: GNU readline library
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/msys/i686/libreadline-6.3.008-7-i686.pkg.tar.xz
      md5: 4e55af837e436aaad9b15df1b89c563f
      mv-src: '*'
      mv-dst: Library/
    win-64:
      url: http://repo.msys2.org/msys/x86_64/libreadline-6.3.008-7-x86_64.pkg.tar.xz
      md5: 6441d0cfe6cb9d3d5e1fd769e59eb8f1
      mv-src: '*'
      mv-dst: Library/
