package:
  name: m2-msys2-libmetalink
  version: 0.1.2
source:
  url: http://repo.msys2.org/msys/sources/libmetalink-0.1.2-2.src.tar.gz
  md5: 936524317a13f7da01ff4676bdb271e2
build:
  number: '2'
requirements:
  run:
  - m2-msys2-msys2-runtime
  - m2-msys2-libexpat
  - m2-msys2-bash
about:
  home: https://launchpad.net/libmetalink
  license: GPL (msys-2.0.dll linkage), MIT
  summary: Metalink XML parser library.
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/msys/i686/libmetalink-0.1.2-2-i686.pkg.tar.xz
      md5: faaf33b04c22b3b3ff0b3e0ae03b3e7c
      mv-src: '*'
      mv-dst: Library/
    win-64:
      url: http://repo.msys2.org/msys/x86_64/libmetalink-0.1.2-2-x86_64.pkg.tar.xz
      md5: ad3a6d5b34b6ada61617367d9e521094
      mv-src: '*'
      mv-dst: Library/
