package:
  name: m2-mingw-w64-tools-git
  version: 5.0.0.4592.90b8472
source:
  url: http://repo.msys2.org/mingw/sources/mingw-w64-tools-git-5.0.0.4592.90b8472-1.src.tar.gz
  md5: 9575aede97a5fc6e5f27919954cd0541
build:
  number: '1'
requirements:
  run:
  - m2-mingw-w64-gcc-libs
about:
  home: http://mingw-w64.sourceforge.net
  license: custom
  summary: MinGW-w64 tools
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/mingw/i686/mingw-w64-i686-tools-git-5.0.0.4592.90b8472-1-any.pkg.tar.xz
      md5: 78d11cdc8e3b5deb9cde63a75944fcdf
      mv-src: mingw32
      mv-dst: Library/mingw-w64
    win-64:
      url: http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-tools-git-5.0.0.4592.90b8472-1-any.pkg.tar.xz
      md5: ebc99e16b08219a383d3fe8d51d579b4
      mv-src: mingw64
      mv-dst: Library/mingw-w64
