package:
  name: m2-msys2-rebase
  version: 4.4.2
source:
  url: http://repo.msys2.org/msys/sources/rebase-4.4.2-1.src.tar.gz
  md5: 34e6487ffc047f7072d6e5b801ae6499
build:
  number: '1'
requirements:
  run:
  - m2-msys2-msys2-runtime
  - m2-msys2-dash
about:
  home: https://www.cygwin.com/
  license: GPL, custom
  summary: The Cygwin rebase distribution contains four utilities, rebase, rebaseall,
    peflags, and peflagsall.
extra:
  msys2-binaries:
    win-32:
      srcpkg: msys/rebase
      url: http://repo.msys2.org/msys/i686/rebase-4.4.2-1-i686.pkg.tar.xz
      md5: befdb099fd5320901c071b1116cc46dd
      mv-src: '*'
      mv-dst: Library/
    win-64:
      srcpkg: msys/rebase
      url: http://repo.msys2.org/msys/x86_64/rebase-4.4.2-1-x86_64.pkg.tar.xz
      md5: a32a4bdd9895aa135e693840ce64162c
      mv-src: '*'
      mv-dst: Library/
