package:
  name: m2-msys2-pacman
  version: 5.0.1.6403.520736d
source:
  url: http://repo.msys2.org/msys/sources/pacman-5.0.1.6403.520736d-1.src.tar.gz
  md5: ac16ddeae0f7eac4286e3762b865d2ac
build:
  number: '1'
requirements:
  run:
  - m2-msys2-bash
  - m2-msys2-gettext
  - m2-msys2-gnupg
  - m2-msys2-msys2-runtime
  - m2-msys2-curl
  - m2-msys2-pacman-mirrors
  - m2-msys2-msys2-keyring
  - m2-msys2-which
  - m2-msys2-bzip2
  - m2-msys2-xz
about:
  home: https://www.archlinux.org/pacman/
  license: GPL
  summary: A library-based package manager with dependency support (MSYS2 port)
extra:
  msys2-binaries:
    win-32:
      srcpkg: msys/pacman
      url: http://repo.msys2.org/msys/i686/pacman-5.0.1.6403.07ca798-1-i686.pkg.tar.xz
      md5: 5dd05ff5579f9200ae578ed9988e724e
      mv-src: '*'
      mv-dst: Library/
    win-64:
      srcpkg: msys/pacman
      url: http://repo.msys2.org/msys/x86_64/pacman-5.0.1.6403.520736d-1-x86_64.pkg.tar.xz
      md5: 862f407dd20e9b394a0f8b3b877f48bd
      mv-src: '*'
      mv-dst: Library/
