package:
  name: m2-msys2-base
  version: '1.0'
requirements:
  run:
  - m2-msys2-bash
  - m2-msys2-bash-completion
  - m2-msys2-catgets
  - m2-msys2-coreutils
  - m2-msys2-dash
  - m2-msys2-file
  - m2-msys2-filesystem
  - m2-msys2-findutils
  - m2-msys2-gawk
  - m2-msys2-gcc-libs
  - m2-msys2-grep
  - m2-msys2-gzip
  - m2-msys2-inetutils
  - m2-msys2-info
  - m2-msys2-less
  - m2-msys2-mintty
  - m2-msys2-msys2-launcher-git
  - m2-msys2-msys2-runtime
  - m2-msys2-ncurses
  - m2-msys2-sed
  - m2-msys2-time
  - m2-msys2-ttyrec
  - m2-msys2-tzcode
  - m2-msys2-util-linux
  - m2-msys2-which
  - m2-msys2-libxml2
  - m2-msys2-make        # added for conda
  - m2-msys2-unzip       # added for conda
  - m2-msys2-diffutils   # added for conda
