package:
  name: m2-msys2-libdb
  version: 5.3.28
source:
  url: http://repo.msys2.org/msys/sources/libdb-5.3.28-2.src.tar.gz
  md5: 936524317a13f7da01ff4676bdb271e2
build:
  number: '2'
requirements:
  run:
  - m2-msys2-gcc-libs
  - m2-msys2-msys2-runtime
about:
  home: http://www.oracle.com/technology/software/products/berkeley-db/index.html
  license: GPL (msys-2.0.dll linkage), custom
  summary: The Berkeley DB embedded database system
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/msys/i686/libdb-5.3.28-2-i686.pkg.tar.xz
      md5: a23f958c1cfa633b3607e2c2022bcc95
      mv-src: '*'
      mv-dst: Library/
    win-64:
      url: http://repo.msys2.org/msys/x86_64/libdb-5.3.28-2-x86_64.pkg.tar.xz
      md5: d475807dbef95e592f2b46af5a82bad4
      mv-src: '*'
      mv-dst: Library/
