package:
  name: m2-msys2-perl-http-date
  version: '6.02'
source:
  url: http://repo.msys2.org/msys/sources/perl-HTTP-Date-6.02-2.src.tar.gz
  md5: 936524317a13f7da01ff4676bdb271e2
build:
  number: '2'
requirements:
  run:
  - m2-msys2-perl
about:
  home: http://search.cpan.org/dist/HTTP-Date
  license: PerlArtistic, GPL
  summary: Date conversion routines
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/msys/i686/perl-HTTP-Date-6.02-2-any.pkg.tar.xz
      md5: a8429c98cb6522d62d0f7eca607352cb
      mv-src: '*'
      mv-dst: Library/
    win-64:
      url: http://repo.msys2.org/msys/x86_64/perl-HTTP-Date-6.02-2-any.pkg.tar.xz
      md5: ebcc88b985678f59591cb2f776b088c3
      mv-src: '*'
      mv-dst: Library/
