package:
  name: m2-msys2-db
  version: 5.3.28
source:
  url: http://repo.msys2.org/msys/sources/db-5.3.28-2.src.tar.gz
  md5: baadc0debaadc0debaadc0debaadc0de
build:
  number: '2'
requirements:
  run:
  - m2-msys2-libdb
about:
  home: http://www.oracle.com/technology/software/products/berkeley-db/index.html
  license: GPL (msys-2.0.dll linkage), custom
  summary: The Berkeley DB embedded database system
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/msys/i686/db-5.3.28-2-i686.pkg.tar.xz
      md5: 47bee1d3307f80796116f81af4292bc1
      mv-src: '*'
      mv-dst: Library/
    win-64:
      url: http://repo.msys2.org/msys/x86_64/db-5.3.28-2-x86_64.pkg.tar.xz
      md5: b7d6e6fd91f2c46bb9e1e486dff99e5c
      mv-src: '*'
      mv-dst: Library/
