package:
  name: m2-msys2-libexpat
  version: 2.1.1
source:
  url: http://repo.msys2.org/msys/sources/libexpat-2.1.1-1.src.tar.gz
  md5: 936524317a13f7da01ff4676bdb271e2
build:
  number: '1'
requirements:
  run:
  - m2-msys2-gcc-libs
about:
  home: http://expat.sourceforge.net/
  license: GPL (msys-2.0.dll linkage), custom
  summary: An XML parser library
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/msys/i686/libexpat-2.1.1-1-i686.pkg.tar.xz
      md5: cbb0f3559729486e3e73d089d0030608
      mv-src: '*'
      mv-dst: Library/
    win-64:
      url: http://repo.msys2.org/msys/x86_64/libexpat-2.1.1-1-x86_64.pkg.tar.xz
      md5: 4371915c5d4aedf8a819c05e8fe3e236
      mv-src: '*'
      mv-dst: Library/
