package:
  name: m2-msys2-msys2-runtime
  version: 2.5.0.17073.1d8ddc7
source:
  url: http://repo.msys2.org/msys/sources/msys2-runtime-2.5.0.17073.1d8ddc7-1.src.tar.gz
  md5: 981bdbd0eb37502dde15c401aa75ca07
build:
  number: '1'
requirements:
  run: []
about:
  home: null
  license: GPL
  summary: Posix emulation engine for Windows
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/msys/i686/msys2-runtime-2.5.0.17073.1439def-1-i686.pkg.tar.xz
      md5: 7520d8f0a028ebcb4da7f5ee6c5e3d7e
      mv-src: '*'
      mv-dst: Library/
    win-64:
      url: http://repo.msys2.org/msys/x86_64/msys2-runtime-2.5.0.17073.1d8ddc7-1-x86_64.pkg.tar.xz
      md5: baee9f992b20408eeef9f15a789a1b95
      mv-src: '*'
      mv-dst: Library/
