package:
  name: m2-mingw-w64-bwidget
  version: 1.9.8
source:
  url: http://repo.msys2.org/mingw/sources/mingw-w64-bwidget-1.9.8-1.src.tar.gz
  md5: 936524317a13f7da01ff4676bdb271e2
build:
  number: '1'
requirements:
  run:
  - m2-mingw-w64-tk
about:
  home: http://core.tcl.tk/bwidget/home
  license: BSD
  summary: A companion to Tcllib, for Tk related packages (mingw-w64)
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/mingw/i686/mingw-w64-i686-bwidget-1.9.8-1-any.pkg.tar.xz
      md5: 9e36cc41379580120712cb7b6b5371b6
      mv-src: mingw32
      mv-dst: Library/mingw-w64
    win-64:
      url: http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-bwidget-1.9.8-1-any.pkg.tar.xz
      md5: e48143bb40b656deb96a92eaf34da961
      mv-src: mingw64
      mv-dst: Library/mingw-w64
