package:
  name: m2-msys2-msys2-launcher-git
  version: 0.3.19.f91905f
source:
  url: http://repo.msys2.org/msys/sources/msys2-launcher-git-0.3.19.f91905f-1.src.tar.gz
  md5: 1195276c001f589da73cd03ffe62c066
build:
  number: '1'
requirements:
  run: []
about:
  home: null
  license: GPL (msys-2.0.dll linkage), MIT
  summary: Helper for launching MSYS2 shells
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/msys/i686/msys2-launcher-git-0.3.19.f91905f-1-i686.pkg.tar.xz
      md5: 5d548b55e167ddade00907f4a6775be7
      mv-src: '*'
      mv-dst: Library/
    win-64:
      url: http://repo.msys2.org/msys/x86_64/msys2-launcher-git-0.3.19.f91905f-1-x86_64.pkg.tar.xz
      md5: 7e55cf32e89008e54af6950cf8ffa58f
      mv-src: '*'
      mv-dst: Library/
