package:
  name: m2-msys2-gcc-libs
  version: 5.3.0
source:
  url: http://repo.msys2.org/msys/sources/gcc-libs-5.3.0-1.src.tar.gz
  md5: 936524317a13f7da01ff4676bdb271e2
build:
  number: '1'
requirements:
  run:
  - m2-msys2-msys2-runtime
about:
  home: http://gcc.gnu.org
  license: GPL, LGPL, FDL, custom
  summary: Runtime libraries shipped by GCC
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/msys/i686/gcc-libs-5.3.0-1-i686.pkg.tar.xz
      md5: 8b570d137de6dcec7c30b34b81ac334b
      mv-src: '*'
      mv-dst: Library/
    win-64:
      url: http://repo.msys2.org/msys/x86_64/gcc-libs-5.3.0-1-x86_64.pkg.tar.xz
      md5: bf27045ff4a4d9199de11b81cb6a5719
      mv-src: '*'
      mv-dst: Library/
