package:
  name: m2-msys2-gcc-libs
  version: 5.3.0
source:
  url: http://repo.msys2.org/msys/sources/gcc-libs-5.3.0-2.src.tar.gz
  md5: 936524317a13f7da01ff4676bdb271e2
build:
  number: '2'
requirements:
  run:
  - m2-msys2-msys2-runtime
about:
  home: http://gcc.gnu.org
  license: GPL, LGPL, FDL, custom
  summary: Runtime libraries shipped by GCC
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/msys/i686/gcc-libs-5.3.0-2-i686.pkg.tar.xz
      md5: 136e9c165e6a24d6597395cd222d9310
      mv-src: '*'
      mv-dst: Library/
    win-64:
      url: http://repo.msys2.org/msys/x86_64/gcc-libs-5.3.0-2-x86_64.pkg.tar.xz
      md5: 1f775224ae15f1f29ad7f81ae4d43f5f
      mv-src: '*'
      mv-dst: Library/
