package:
  name: m2-msys2-libiconv-devel
  version: '1.14'
source:
  url: http://repo.msys2.org/msys/sources/libiconv-devel-1.14-2.src.tar.gz
  md5: baadc0debaadc0debaadc0debaadc0de
build:
  number: '2'
requirements:
  run:
  - m2-msys2-libiconv
about:
  home: http://www.gnu.org/software/libiconv/
  license: GPL (msys-2.0.dll linkage), LGPL
  summary: libiconv headers and libraries
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/msys/i686/libiconv-devel-1.14-2-i686.pkg.tar.xz
      md5: eed8aeaab38a4d343a3e3fb22927d268
      mv-src: '*'
      mv-dst: Library/
    win-64:
      url: http://repo.msys2.org/msys/x86_64/libiconv-devel-1.14-2-x86_64.pkg.tar.xz
      md5: 9f42411c3e55d78b02c846bbad287fc7
      mv-src: '*'
      mv-dst: Library/
