package:
  name: m2-mingw-w64-headers-git
  version: 5.0.0.4627.53be55d
source:
  url: http://repo.msys2.org/mingw/sources/mingw-w64-headers-git-5.0.0.4627.53be55d-1.src.tar.gz
  md5: baadc0debaadc0debaadc0debaadc0de
build:
  number: '1'
requirements:
  run: []
about:
  home: http://mingw-w64.sourceforge.net
  license: custom
  summary: MinGW-w64 headers for Windows
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/mingw/i686/mingw-w64-i686-headers-git-5.0.0.4627.6baeb9d-1-any.pkg.tar.xz
      md5: 6491490103e61612e7ef69dbd0246ac9
      mv-src: mingw32
      mv-dst: Library/mingw-w64
    win-64:
      url: http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-headers-git-5.0.0.4627.53be55d-1-any.pkg.tar.xz
      md5: 54640b5ad239c3f761b76493afd52145
      mv-src: mingw64
      mv-dst: Library/mingw-w64
