package:
  name: m2-mingw-w64-gettext
  version: 0.19.6
source:
  url: http://repo.msys2.org/mingw/sources/mingw-w64-gettext-0.19.6-2.src.tar.gz
  md5: d521a945fcce911d1c29e2d4377861b8
build:
  number: '2'
requirements:
  run:
  - m2-mingw-w64-expat
  - m2-mingw-w64-gcc-libs
  - m2-mingw-w64-libiconv
about:
  home: http://www.gnu.org/software/gettext/
  license: GPL3, partial:LGPL2.1
  summary: GNU internationalization library (mingw-w64)
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/mingw/i686/mingw-w64-i686-gettext-0.19.6-2-any.pkg.tar.xz
      md5: 4e385b64a99c1397df474d5d91d10b9a
      mv-src: mingw32
      mv-dst: Library/mingw-w64
    win-64:
      url: http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-gettext-0.19.6-2-any.pkg.tar.xz
      md5: c18a06761351330ba290ff50a4d86563
      mv-src: mingw64
      mv-dst: Library/mingw-w64
