package:
  name: m2-mingw-w64-libxml2
  version: 2.9.3
source:
  url: http://repo.msys2.org/mingw/sources/mingw-w64-libxml2-2.9.3-1.src.tar.gz
  md5: 1acb47bd2c674a0ca53952cd3367aaff
build:
  number: '1'
requirements:
  run:
  - m2-mingw-w64-gcc-libs
  - m2-mingw-w64-gettext
  - m2-mingw-w64-xz
  - m2-mingw-w64-zlib
about:
  home: http://www.xmlsoft.org/
  license: MIT
  summary: XML parsing library, version 2 (mingw-w64)
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/mingw/i686/mingw-w64-i686-libxml2-2.9.3-1-any.pkg.tar.xz
      md5: 7815dc6a58848250511bdb6b3266f760
      mv-src: mingw32
      mv-dst: Library/mingw-w64
    win-64:
      url: http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-libxml2-2.9.3-1-any.pkg.tar.xz
      md5: 06cc4d4d30e7df0b38916a836ec6fbbf
      mv-src: mingw64
      mv-dst: Library/mingw-w64
