package:
  name: m2-mingw-w64-libxml2
  version: 2.9.3
source:
  url: http://repo.msys2.org/mingw/sources/mingw-w64-libxml2-2.9.3-2.src.tar.gz
  md5: 77805e10593a41f2de3b886a3b9423d6
build:
  number: '2'
requirements:
  run:
  - m2-mingw-w64-gcc-libs
  - m2-mingw-w64-gettext
  - m2-mingw-w64-xz
  - m2-mingw-w64-zlib
about:
  home: http://www.xmlsoft.org/
  license: MIT
  summary: XML parsing library, version 2 (mingw-w64)
extra:
  msys2-binaries:
    win-32:
      srcpkg: mingw32/mingw-w64-i686-libxml2
      url: http://repo.msys2.org/mingw/i686/mingw-w64-i686-libxml2-2.9.3-2-any.pkg.tar.xz
      md5: 7ed8f48ae2c23de289a242d6794c7cda
      mv-src: mingw32
      mv-dst: Library/mingw-w64
    win-64:
      srcpkg: mingw64/mingw-w64-x86_64-libxml2
      url: http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-libxml2-2.9.3-2-any.pkg.tar.xz
      md5: a0ca811b3fa42316e3b92bd00af186df
      mv-src: mingw64
      mv-dst: Library/mingw-w64
