package:
  name: m2-mingw-w64-c-ares
  version: 1.11.0
source:
  url: http://repo.msys2.org/mingw/sources/mingw-w64-c-ares-1.11.0-1.src.tar.gz
  md5: c45dd73d19056c4c825621c1d427fc41
build:
  number: '1'
requirements:
  run: []
about:
  home: http://c-ares.haxx.se/
  license: MIT, BSD
  summary: C library that performs DNS requests and name resolves asynchronously (mingw-w64)
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/mingw/i686/mingw-w64-i686-c-ares-1.11.0-1-any.pkg.tar.xz
      md5: 033a2a61092e32ecb0e2ebabf92fadf7
      mv-src: mingw32
      mv-dst: Library/mingw-w64
    win-64:
      url: http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-c-ares-1.11.0-1-any.pkg.tar.xz
      md5: 052955279182878a8414c3da1ed232a8
      mv-src: mingw64
      mv-dst: Library/mingw-w64
