package:
  name: m2-msys2-bison
  version: 3.0.4
source:
  url: http://repo.msys2.org/msys/sources/bison-3.0.4-1.src.tar.gz
  md5: baadc0debaadc0debaadc0debaadc0de
build:
  number: '1'
requirements:
  run:
  - m2-msys2-m4
  - m2-msys2-bash
about:
  home: http://www.gnu.org/software/bison/bison.html
  license: GPL (msys-2.0.dll linkage), GPL3
  summary: The GNU general-purpose parser generator
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/msys/i686/bison-3.0.4-1-i686.pkg.tar.xz
      md5: 9abcb3a39de92267c51837989f53f300
      mv-src: '*'
      mv-dst: Library/
    win-64:
      url: http://repo.msys2.org/msys/x86_64/bison-3.0.4-1-x86_64.pkg.tar.xz
      md5: 80aa62d48ddd4fbc3ac5d19304dadc79
      mv-src: '*'
      mv-dst: Library/
