package:
  name: m2-mingw-w64-libjpeg-turbo
  version: 1.4.2
source:
  url: http://repo.msys2.org/mingw/sources/mingw-w64-libjpeg-turbo-1.4.2-2.src.tar.gz
  md5: b604f1b882a798ee14d414c65e3ea48b
build:
  number: '2'
requirements:
  run:
  - m2-mingw-w64-gcc-libs
about:
  home: http://libjpeg-turbo.virtualgl.org
  license: custom:BSD-like
  summary: JPEG image codec with accelerated baseline compression and decompression
    (mingw-w64)
extra:
  msys2-binaries:
    win-32:
      srcpkg: mingw32/mingw-w64-i686-libjpeg-turbo
      url: http://repo.msys2.org/mingw/i686/mingw-w64-i686-libjpeg-turbo-1.4.2-2-any.pkg.tar.xz
      md5: cee4b57b3c55c8914efd98d551ddc3fe
      mv-src: mingw32
      mv-dst: Library/mingw-w64
    win-64:
      srcpkg: mingw64/mingw-w64-x86_64-libjpeg-turbo
      url: http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-libjpeg-turbo-1.4.2-2-any.pkg.tar.xz
      md5: 63eed7a02be8918fa3759bea38d34173
      mv-src: mingw64
      mv-dst: Library/mingw-w64
