package:
  name: m2-mingw-w64-pkg-config
  version: 0.29.1
source:
  url: http://repo.msys2.org/mingw/sources/mingw-w64-pkg-config-0.29.1-1.src.tar.gz
  md5: 98d3161955b1728f628b5697ff3db45e
build:
  number: '1'
requirements:
  run:
  - m2-mingw-w64-libwinpthread-git
about:
  home: https://www.freedesktop.org/wiki/Software/pkg-config/
  license: GPL
  summary: A system for managing library compile/link flags (mingw-w64)
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/mingw/i686/mingw-w64-i686-pkg-config-0.29.1-1-any.pkg.tar.xz
      md5: d6abf7565d0119724350cc943e3c0016
      mv-src: mingw32
      mv-dst: Library/mingw-w64
    win-64:
      url: http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-pkg-config-0.29.1-1-any.pkg.tar.xz
      md5: bc2ee66ec1c011e8c87f373fd8be501b
      mv-src: mingw64
      mv-dst: Library/mingw-w64
