package:
  name: m2-msys2-libintl
  version: 0.19.7
source:
  url: http://repo.msys2.org/msys/sources/libintl-0.19.7-3.src.tar.gz
  md5: 936524317a13f7da01ff4676bdb271e2
build:
  number: '3'
requirements:
  run:
  - m2-msys2-gcc-libs
  - m2-msys2-libiconv
about:
  home: https://www.gnu.org/software/gettext/
  license: GPL
  summary: GNU Internationalization runtime library
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/msys/i686/libintl-0.19.7-3-i686.pkg.tar.xz
      md5: 2ef05ce06b4dc8269293a6dd30ec9c68
      mv-src: '*'
      mv-dst: Library/
    win-64:
      url: http://repo.msys2.org/msys/x86_64/libintl-0.19.7-3-x86_64.pkg.tar.xz
      md5: a67e364427d0fab79500cfbd78a52f69
      mv-src: '*'
      mv-dst: Library/
