package:
  name: m2-mingw-w64-zeromq
  version: 4.1.3
source:
  url: http://repo.msys2.org/mingw/sources/mingw-w64-zeromq-4.1.3-1.src.tar.gz
  md5: 49eefa00b1b1e12dfae7ec4eff886749
build:
  number: '1'
requirements:
  run:
  - m2-mingw-w64-libsodium
about:
  home: http://www.zeromq.org
  license: LGPL
  summary: Fast messaging system built on sockets, C and C++ bindings. aka 0MQ, ZMQ
    (mingw-w64)
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/mingw/i686/mingw-w64-i686-zeromq-4.1.3-1-any.pkg.tar.xz
      md5: 9cf91dc5a6ee2714f8882c05ee3a3cbc
      mv-src: mingw32
      mv-dst: Library/mingw-w64
    win-64:
      url: http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-zeromq-4.1.3-1-any.pkg.tar.xz
      md5: bb0b5775956bf60a017fb53b6447cf9f
      mv-src: mingw64
      mv-dst: Library/mingw-w64
