package:
  name: m2-mingw-w64-gmp
  version: 6.1.0
source:
  url: http://repo.msys2.org/mingw/sources/mingw-w64-gmp-6.1.0-1.src.tar.gz
  md5: ebf85c5b344d118e70e45b6147663422
build:
  number: '1'
requirements:
  run: []
about:
  home: http://gmplib.org/
  license: LGPL3
  summary: A free library for arbitrary precision arithmetic (mingw-w64)
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/mingw/i686/mingw-w64-i686-gmp-6.1.0-1-any.pkg.tar.xz
      md5: 028dc3e0d92bd5a59c7fb089da67d3e0
      mv-src: mingw32
      mv-dst: Library/mingw-w64
    win-64:
      url: http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-gmp-6.1.0-1-any.pkg.tar.xz
      md5: 820243e6e54f51e81bbd43849efc46ac
      mv-src: mingw64
      mv-dst: Library/mingw-w64
