package:
  name: m2-msys2-pacman-mirrors
  version: '20160112'
source:
  url: http://repo.msys2.org/msys/sources/pacman-mirrors-20160112-1.src.tar.gz
  md5: 39ec6606a2fe0da7b40e821334e859e7
build:
  number: '1'
requirements:
  run: []
about:
  home: http://msys2.sourceforge.net/
  license: GPL
  summary: MSYS2 mirror list for use by pacman
extra:
  msys2-binaries:
    win-32:
      srcpkg: msys/pacman-mirrors
      url: http://repo.msys2.org/msys/i686/pacman-mirrors-20160112-1-any.pkg.tar.xz
      md5: eb4f26206b43f338752cd95e3c561b4f
      mv-src: '*'
      mv-dst: Library/
    win-64:
      srcpkg: msys/pacman-mirrors
      url: http://repo.msys2.org/msys/x86_64/pacman-mirrors-20160112-1-any.pkg.tar.xz
      md5: 6a4c6d1d485f35972d0e8809e1c31e47
      mv-src: '*'
      mv-dst: Library/
