package:
  name: m2-msys2-help2man
  version: 1.47.3
source:
  url: http://repo.msys2.org/msys/sources/help2man-1.47.3-1.src.tar.gz
  md5: d865e4349fdf5015ab667a768bb7f6b2
build:
  number: '1'
requirements:
  run:
  - m2-msys2-perl-locale-gettext
  - m2-msys2-libintl
about:
  home: http://www.gnu.org/software/help2man/
  license: GPL
  summary: Conversion tool to create man files
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/msys/i686/help2man-1.47.3-1-i686.pkg.tar.xz
      md5: 734cbfcb1c7e193e1bc344413ca291d5
      mv-src: '*'
      mv-dst: Library/
    win-64:
      url: http://repo.msys2.org/msys/x86_64/help2man-1.47.3-1-x86_64.pkg.tar.xz
      md5: 4334b7d9fb5896dc8ee18e8f304db425
      mv-src: '*'
      mv-dst: Library/
