package:
  name: m2-msys2-curl
  version: 7.47.1
source:
  url: http://repo.msys2.org/msys/sources/curl-7.47.1-2.src.tar.gz
  md5: decbcaa6db05719c46217d880778d4d9
build:
  number: '2'
requirements:
  run:
  - m2-msys2-ca-certificates
  - m2-msys2-libcurl
  - m2-msys2-libcrypt
  - m2-msys2-libmetalink
  - m2-msys2-openssl
  - m2-msys2-zlib
about:
  home: https://curl.haxx.se
  license: GPL (msys-2.0.dll linkage), MIT
  summary: Multi-protocol file transfer utility
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/msys/i686/curl-7.47.1-2-i686.pkg.tar.xz
      md5: 1e4edc4a8c631e62004b38b1f4b94add
      mv-src: '*'
      mv-dst: Library/
    win-64:
      url: http://repo.msys2.org/msys/x86_64/curl-7.47.1-2-x86_64.pkg.tar.xz
      md5: b72221272f3cc3e974622ff59cacde61
      mv-src: '*'
      mv-dst: Library/
