package:
  name: m2-msys2-perl-termreadkey
  version: '2.33'
source:
  url: http://repo.msys2.org/msys/sources/perl-TermReadKey-2.33-1.src.tar.gz
  md5: 78d241f4979cfbd5242817647e71ea18
build:
  number: '1'
requirements:
  run:
  - m2-msys2-perl
about:
  home: http://search.cpan.org/~jstowe/TermReadKey/
  license: GPL (msys-2.0.dll linkage), custom
  summary: Provides simple control over terminal driver modes
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/msys/i686/perl-TermReadKey-2.33-1-i686.pkg.tar.xz
      md5: 20ae085e980c7844ad0bc66fca44f488
      mv-src: '*'
      mv-dst: Library/
    win-64:
      url: http://repo.msys2.org/msys/x86_64/perl-TermReadKey-2.33-1-x86_64.pkg.tar.xz
      md5: b7e74d5fe02dd287eb8dab4f9a48f0fd
      mv-src: '*'
      mv-dst: Library/
