package:
  name: m2-msys2-tftp-hpa
  version: '5.2'
source:
  url: http://repo.msys2.org/msys/sources/tftp-hpa-5.2-1.src.tar.gz
  md5: 936524317a13f7da01ff4676bdb271e2
build:
  number: '1'
requirements:
  run:
  - m2-msys2-libreadline
about:
  home: http://www.kernel.org/pub/software/network/tftp/tftp-hpa/
  license: GPL, BSD
  summary: Official tftp server
extra:
  msys2-binaries:
    win-32:
      srcpkg: msys/tftp-hpa
      url: http://repo.msys2.org/msys/i686/tftp-hpa-5.2-1-i686.pkg.tar.xz
      md5: 750ca6d06ec424add9db69fbe1430973
      mv-src: '*'
      mv-dst: Library/
    win-64:
      srcpkg: msys/tftp-hpa
      url: http://repo.msys2.org/msys/x86_64/tftp-hpa-5.2-1-x86_64.pkg.tar.xz
      md5: 89cf7705573d092772fd4cd809171ba0
      mv-src: '*'
      mv-dst: Library/
