package:
  name: m2-msys2-perl-uri
  version: '1.68'
source:
  url: http://repo.msys2.org/msys/sources/perl-URI-1.68-1.src.tar.gz
  md5: 936524317a13f7da01ff4676bdb271e2
build:
  number: '1'
requirements:
  run:
  - m2-msys2-perl
about:
  home: http://search.cpan.org/dist/URI/
  license: GPL (msys-2.0.dll linkage), PerlArtistic
  summary: Uniform Resource Identifiers (absolute and relative)
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/msys/i686/perl-URI-1.68-1-any.pkg.tar.xz
      md5: 786de60c79a8e8b8550601ea766f4497
      mv-src: '*'
      mv-dst: Library/
    win-64:
      url: http://repo.msys2.org/msys/x86_64/perl-URI-1.68-1-any.pkg.tar.xz
      md5: 19b76df1185bdc13be77c0668f8ee28c
      mv-src: '*'
      mv-dst: Library/
