package:
  name: m2-msys2-libgdbm
  version: '1.11'
source:
  url: http://repo.msys2.org/msys/sources/libgdbm-1.11-3.src.tar.gz
  md5: 936524317a13f7da01ff4676bdb271e2
build:
  number: '3'
requirements:
  run:
  - m2-msys2-gcc-libs
about:
  home: http://www.gnu.org/software/gdbm/gdbm.html
  license: GPL (msys-2.0.dll linkage), GPL3
  summary: GNU database library
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/msys/i686/libgdbm-1.11-3-i686.pkg.tar.xz
      md5: 4ad71d2a18724b1bc9e5d481b90b9f58
      mv-src: '*'
      mv-dst: Library/
    win-64:
      url: http://repo.msys2.org/msys/x86_64/libgdbm-1.11-3-x86_64.pkg.tar.xz
      md5: 3d787752482705aaa93bbe6e20850dc0
      mv-src: '*'
      mv-dst: Library/
