package:
  name: m2-mingw-w64-gnutls
  version: 3.4.11
source:
  url: http://repo.msys2.org/mingw/sources/mingw-w64-gnutls-3.4.11-1.src.tar.gz
  md5: 0d6cc3f4491575ad3ccf0655017cb5a6
build:
  number: '1'
requirements:
  run:
  - m2-mingw-w64-gcc-libs
  - m2-mingw-w64-gmp
  - m2-mingw-w64-libidn
  - m2-mingw-w64-libsystre
  - m2-mingw-w64-libtasn1
  - m2-mingw-w64-nettle
  - m2-mingw-w64-p11-kit
  - m2-mingw-w64-zlib
about:
  home: http://www.gnutls.org/
  license: GPL3, LGPL2.1
  summary: A library which provides a secure layer over a reliable transport layer
    (mingw-w64)
extra:
  msys2-binaries:
    win-32:
      srcpkg: mingw32/mingw-w64-i686-gnutls
      url: http://repo.msys2.org/mingw/i686/mingw-w64-i686-gnutls-3.4.11-1-any.pkg.tar.xz
      md5: c47b5c2488982ea198333cc93d01012f
      mv-src: mingw32
      mv-dst: Library/mingw-w64
    win-64:
      srcpkg: mingw64/mingw-w64-x86_64-gnutls
      url: http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-gnutls-3.4.11-1-any.pkg.tar.xz
      md5: 39334e4b3553eb1186db8b717986316a
      mv-src: mingw64
      mv-dst: Library/mingw-w64
