package:
  name: m2-mingw-w64-libogg
  version: 1.3.2
source:
  url: http://repo.msys2.org/mingw/sources/mingw-w64-libogg-1.3.2-2.src.tar.gz
  md5: 936524317a13f7da01ff4676bdb271e2
build:
  number: '2'
requirements:
  run: []
about:
  home: http://xiph.org
  license: BSD
  summary: Ogg bitstream and framing library (mingw-w64)
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/mingw/i686/mingw-w64-i686-libogg-1.3.2-2-any.pkg.tar.xz
      md5: 0d0943af6264c6357f2d92de75c44ecf
      mv-src: mingw32
      mv-dst: Library/mingw-w64
    win-64:
      url: http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-libogg-1.3.2-2-any.pkg.tar.xz
      md5: 109edf3d0e1303bc9e2ff4327e8ba99f
      mv-src: mingw64
      mv-dst: Library/mingw-w64
