package:
  name: m2-msys2-glib2
  version: 2.44.1
source:
  url: http://repo.msys2.org/msys/sources/glib2-2.44.1-1.src.tar.gz
  md5: b70177e1fe417c75f6a8bebe24a082f3
build:
  number: '1'
requirements:
  run:
  - m2-msys2-libxslt
  - m2-msys2-libpcre
  - m2-msys2-libffi
  - m2-msys2-libiconv
  - m2-msys2-zlib
about:
  home: http://www.gtk.org/
  license: GPL (msys-2.0.dll linkage), LGPL
  summary: Common C routines used by GTK+ and other libs
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/msys/i686/glib2-2.44.1-1-i686.pkg.tar.xz
      md5: 4dea1ac082e576c90cd2f8aaa39f2597
      mv-src: '*'
      mv-dst: Library/
    win-64:
      url: http://repo.msys2.org/msys/x86_64/glib2-2.44.1-1-x86_64.pkg.tar.xz
      md5: f29cc32c9068106e71217627b4459656
      mv-src: '*'
      mv-dst: Library/
