{% set posix = 'm2-msys2-' if win else '' %}
{% set native = 'm2-mingw-w64-' if win else '' %}

package:
  name: r-testthat
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "0.11.0"

source:
  fn: testthat_0.11.0.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/testthat_0.11.0.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/testthat/testthat_0.11.0.tar.gz


  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: devtools
requirements:
  build:
    - r-base
    - r-crayon
    - r-digest
    - r-praise
    - {{posix}}base       # [win]
    - {{posix}}zip        # [win]
    - {{native}}toolchain # [win]
    - gcc                 # [not win]

  run:
    - r-base
    - r-crayon
    - r-digest
    - r-praise

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('testthat')" # [not win]
    - "\"%R%\" -e \"library('testthat')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/hadley/testthat
  license: MIT + file LICENSE
  summary: A unit testing system designed to be fun, flexible and easy to set up.
  license_family: MIT

# The original CRAN metadata for this package was:

# Package: testthat
# Version: 0.11.0
# Title: Unit Testing for R
# Description: A unit testing system designed to be fun, flexible and easy to set up.
# Authors@R: c( person("Hadley", "Wickham", , "hadley@rstudio.com", c("aut", "cre")), person("RStudio", role = "cph") )
# URL: https://github.com/hadley/testthat
# BugReports: https://github.com/hadley/testthat/issues
# Depends: R (>= 3.1.0), methods
# Imports: digest, crayon, praise
# Suggests: devtools
# License: MIT + file LICENSE
# Collate: 'auto-test.r' 'colour-text.r' 'compare.r' 'context.r' 'describe.r' 'evaluate-promise.r' 'expect-that.r' 'expectation.r' 'expectations-equality.R' 'expectations-matches.R' 'expectations-old.R' 'expectations-silent.R' 'expectations.r' 'make-expectation.r' 'mock.r' 'praise.R' 'reporter.r' 'reporter-check.R' 'reporter-list.r' 'reporter-minimal.r' 'reporter-multi.r' 'reporter-rstudio.R' 'reporter-silent.r' 'reporter-stop.r' 'reporter-summary.r' 'reporter-tap.r' 'reporter-teamcity.r' 'reporter-zzz.r' 'test-example.R' 'test-files.r' 'test-package.r' 'test-results.r' 'test-that.r' 'traceback.r' 'utils.r' 'watcher.r'
# NeedsCompilation: yes
# Packaged: 2015-10-13 20:53:56 UTC; hadley
# Author: Hadley Wickham [aut, cre], RStudio [cph]
# Maintainer: Hadley Wickham <hadley@rstudio.com>
# Repository: CRAN
# Date/Publication: 2015-10-14 09:54:00

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
