package:
  name: m2-msys2-gzip
  version: '1.6'
source:
  url: http://repo.msys2.org/msys/sources/gzip-1.6-1.src.tar.gz
  md5: baadc0debaadc0debaadc0debaadc0de
build:
  number: '1'
requirements:
  run:
  - m2-msys2-msys2-runtime
  - m2-msys2-bash
  - m2-msys2-less
about:
  home: http://www.gnu.org/software/gzip/
  license: GPL (msys-2.0.dll linkage), GPL3
  summary: GNU compression utility
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/msys/i686/gzip-1.6-1-i686.pkg.tar.xz
      md5: 94800a3f563576957ee94592c4b6f7e8
      mv-src: '*'
      mv-dst: Library/
    win-64:
      url: http://repo.msys2.org/msys/x86_64/gzip-1.6-1-x86_64.pkg.tar.xz
      md5: 779f5fd1c53ab531235adf2ebf80a7c9
      mv-src: '*'
      mv-dst: Library/
