package:
  name: m2-msys2-automake1.7
  version: 1.7.9
source:
  url: http://repo.msys2.org/msys/sources/automake1.7-1.7.9-2.src.tar.gz
  md5: baadc0debaadc0debaadc0debaadc0de
build:
  number: '2'
requirements:
  run:
  - m2-msys2-perl
  - m2-msys2-bash
about:
  home: http://www.gnu.org/software/automake
  license: GPL
  summary: A GNU tool for automatically creating Makefiles
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/msys/i686/automake1.7-1.7.9-2-any.pkg.tar.xz
      md5: 1e897e44f2f41d1ed82a7e02ae035f39
      mv-src: '*'
      mv-dst: Library/
    win-64:
      url: http://repo.msys2.org/msys/x86_64/automake1.7-1.7.9-2-any.pkg.tar.xz
      md5: c575c10691d4fac8c37895ba6f2cab75
      mv-src: '*'
      mv-dst: Library/
