package:
  name: m2-mingw-w64-nettle
  version: 3.1.1
source:
  url: http://repo.msys2.org/mingw/sources/mingw-w64-nettle-3.1.1-3.src.tar.gz
  md5: 48ae066e37acf5252ce935c0bdff6480
build:
  number: '3'
requirements:
  run:
  - m2-mingw-w64-gcc-libs
  - m2-mingw-w64-gmp
about:
  home: http://www.lysator.liu.se/~nisse/nettle
  license: LGPL
  summary: A low-level cryptographic library (mingw-w64)
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/mingw/i686/mingw-w64-i686-nettle-3.1.1-3-any.pkg.tar.xz
      md5: cfab2e45d0e2830e3b8616f1643db860
      mv-src: mingw32
      mv-dst: Library/mingw-w64
    win-64:
      url: http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-nettle-3.1.1-3-any.pkg.tar.xz
      md5: a81eeb2cbda097dfdb10cf8a014b9868
      mv-src: mingw64
      mv-dst: Library/mingw-w64
