package:
  name: m2-msys2-diffstat
  version: '1.58'
source:
  url: http://repo.msys2.org/msys/sources/diffstat-1.58-1.src.tar.gz
  md5: baadc0debaadc0debaadc0debaadc0de
build:
  number: '1'
requirements:
  run:
  - m2-msys2-msys2-runtime
about:
  home: http://invisible-island.net/diffstat
  license: GPL (msys-2.0.dll linkage), MIT
  summary: Display a histogram of diff changes
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/msys/i686/diffstat-1.58-1-i686.pkg.tar.xz
      md5: 77054dab87ebb9c8b81d305d131a46e9
      mv-src: '*'
      mv-dst: Library/
    win-64:
      url: http://repo.msys2.org/msys/x86_64/diffstat-1.58-1-x86_64.pkg.tar.xz
      md5: 8aab604cc2aa3873c850cffbd2fa80f8
      mv-src: '*'
      mv-dst: Library/
