package:
  name: m2-mingw-w64-gcc
  version: 5.3.0
source:
  url: http://repo.msys2.org/mingw/sources/mingw-w64-gcc-5.3.0-2.src.tar.gz
  md5: eacc14b60771ae2272a5afb5b9883223
build:
  number: '2'
requirements:
  run:
  - m2-mingw-w64-binutils
  - m2-mingw-w64-crt-git
  - m2-mingw-w64-headers-git
  - m2-mingw-w64-isl
  - m2-mingw-w64-libiconv
  - m2-mingw-w64-mpc
  - m2-mingw-w64-gcc-libs
  - m2-mingw-w64-windows-default-manifest
  - m2-mingw-w64-winpthreads-git
  - m2-mingw-w64-zlib
about:
  home: http://gcc.gnu.org
  license: GPL, LGPL, FDL, custom
  summary: GNU Compiler Collection (C,C++,OpenMP) for MinGW-w64
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/mingw/i686/mingw-w64-i686-gcc-5.3.0-2-any.pkg.tar.xz
      md5: 77762a01f8e54ce65127e05b64f9b090
      mv-src: mingw32
      mv-dst: Library/mingw-w64
    win-64:
      url: http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-gcc-5.3.0-2-any.pkg.tar.xz
      md5: 10f226fb45196ba5a6db6b5ed5967d9e
      mv-src: mingw64
      mv-dst: Library/mingw-w64
