package:
  name: m2-mingw-w64-xz
  version: 5.2.1
source:
  url: http://repo.msys2.org/mingw/sources/mingw-w64-xz-5.2.1-3.src.tar.gz
  md5: 936524317a13f7da01ff4676bdb271e2
build:
  number: '3'
requirements:
  run:
  - m2-mingw-w64-gcc-libs
  - m2-mingw-w64-gettext
about:
  home: http://tukaani.org/xz
  license: partial:PublicDomain, partial:LGPL2.1+, partial:GPL2+
  summary: Library and command line tools for XZ and LZMA compressed files (mingw-w64)
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/mingw/i686/mingw-w64-i686-xz-5.2.1-3-any.pkg.tar.xz
      md5: f3b4633754b7c24091409b40d0665831
      mv-src: mingw32
      mv-dst: Library/mingw-w64
    win-64:
      url: http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-xz-5.2.1-3-any.pkg.tar.xz
      md5: 9b74a2e7f1699cc078aaaa153194bcd3
      mv-src: mingw64
      mv-dst: Library/mingw-w64
