package:
  name: m2-msys2-ca-certificates
  version: '20150426'
source:
  url: http://repo.msys2.org/msys/sources/ca-certificates-20150426-1.src.tar.gz
  md5: baadc0debaadc0debaadc0debaadc0de
build:
  number: '1'
requirements:
  run:
  - m2-msys2-bash
  - m2-msys2-openssl
  - m2-msys2-findutils
  - m2-msys2-coreutils
  - m2-msys2-sed
  - m2-msys2-p11-kit
about:
  home: http://www.mozilla.org/projects/security/certs/
  license: MPL, GPL
  summary: Common CA certificates
extra:
  msys2-binaries:
    win-32:
      url: http://repo.msys2.org/msys/i686/ca-certificates-20150426-1-any.pkg.tar.xz
      md5: bf0a485ac68cd73bbd0bb1c9ea345c64
      mv-src: '*'
      mv-dst: Library/
    win-64:
      url: http://repo.msys2.org/msys/x86_64/ca-certificates-20150426-1-any.pkg.tar.xz
      md5: f41511bb6d0902b7316efc88605d8382
      mv-src: '*'
      mv-dst: Library/
